//! Operation registry and shared types for the node graph engine.
//!
//! This module defines the [`Operation`] enum (generated by the [`operations!`] macro),
//! the hierarchical [`OperationListItem`] menu structure, and common types used by
//! all operation implementations such as [`OperationResponse`] and [`OperationError`].

use crate::value::{Value, ValueType};
use crate::input::Input;
use crate::float_image::FloatImage;
use serde::{Deserialize, Serialize};
use core::fmt::Debug;
use std::sync::Arc;
use std::time::Duration;
use crate::node_settings::NodeSettings;
use crate::output::Output;

/// Numeric operations (inputs, arithmetic, interpolation, algebra, random, cast, logarithmic).
pub mod numbers;
/// Image operations (inputs, outputs, transforms, adjustments, blur, filter, noise, etc.).
pub mod images;
/// Color operations (inputs, outputs, blending, analysis).
pub mod colors;
/// Logic operations (boolean, comparison, flow control).
pub mod logic;
/// Text operations (clipboard).
pub mod text;

/// Successful result of executing a node operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OperationResponse {
    /// One response per output slot, carrying the computed value.
    pub responses: Vec<OutputResponse>,
    /// Wall-clock time the operation took to execute.
    pub time: Duration,
}

/// A single output value produced by an operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutputResponse {
    /// The computed output value.
    pub value: Value,
}

/// Error returned when an operation fails to execute.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OperationError {
    /// Per-input errors: each entry is `(input_index, error_message)`.
    pub input_errors: Vec<(usize, String)>,
    /// An error on the node itself, independent of any particular input.
    pub node_error: Option<String>,
}

/// Converts an input value to the target type, pushing any error to `errors`.
/// Returns `Some(value)` on success, `None` on failure (error is recorded).
pub fn convert_input(
    inputs: &[Input],
    index: usize,
    target_type: ValueType,
    errors: &mut Vec<(usize, String)>,
) -> Option<Value> {
    match inputs[index].value.try_convert_to(target_type) {
        Ok(v) => Some(v),
        Err(e) => {
            errors.push((index, e.message));
            None
        }
    }
}

/// A node in the hierarchical operation menu tree.
///
/// The GUI uses this to build the "Add Node" context menu with nested categories.
#[derive(Clone)]
pub enum OperationListItem {
    /// A named folder that contains child items (subcategories or operations).
    Category {
        /// Display name for the category.
        name: String,
        /// Child items within this category.
        operation_list_items: Vec<OperationListItem>,
    },
    /// A leaf item representing a single operation that can be added to the graph.
    Operation {
        /// The operation variant to instantiate when selected.
        operation: Operation,
    },
    /// Placeholder for adding a subgraph node.
    Subgraph
}

impl OperationListItem {
    /// Returns the display name for sorting: category name or operation settings name.
    fn sort_name(&self) -> String {
        match self {
            OperationListItem::Category { name, .. } => name.clone(),
            OperationListItem::Operation { operation } => operation.settings().name,
            OperationListItem::Subgraph => "subgraph".to_string(),
        }
    }

    /// Recursively orders menu items: the "input" subcategory first, then
    /// "output", then everything else alphabetically by name. Applied at every
    /// category depth so an "images" category and a nested "adjustments"
    /// category both follow the same rule.
    pub fn sort_alphabetically(items: &mut [OperationListItem]) {
        items.sort_by(|a, b| {
            let ra = Self::menu_rank(a);
            let rb = Self::menu_rank(b);
            ra.cmp(&rb).then_with(|| a.sort_name().cmp(&b.sort_name()))
        });
        for item in items.iter_mut() {
            if let OperationListItem::Category { operation_list_items, .. } = item {
                Self::sort_alphabetically(operation_list_items);
            }
        }
    }

    /// Sort rank pinning "input" and "output" subcategories to the top of
    /// their siblings; everything else falls through to alphabetical order.
    fn menu_rank(item: &OperationListItem) -> u8 {
        match item {
            OperationListItem::Category { name, .. } if name == "input" => 0,
            OperationListItem::Category { name, .. } if name == "output" => 1,
            _ => 2,
        }
    }
}

/// Creates a 1x1 opaque white 4-channel FloatImage wrapped in an `Arc`.
///
/// Used as the default placeholder image for image-typed inputs.
pub fn default_image() -> Arc<FloatImage> {
    Arc::new(FloatImage::from_pixel(1, 1, 4, &[1.0, 1.0, 1.0, 1.0]))
}

/// Reference resolution at which a resolution-independent spatial value equals
/// its literal pixel amount.
///
/// Spatial effect parameters (blur radii, morphology radii, glow/shadow sizes,
/// offsets, etc.) are authored as "pixels at 1024px" and scaled to the actual
/// image via [`scale_to_resolution`], so the *same value* produces the *same
/// relative* result at any resolution — design at 512px, render at 4096px, and
/// the numbers don't change.
pub const REFERENCE_RESOLUTION: f32 = 1024.0;

/// Scales a spatial value expressed in reference pixels (see
/// [`REFERENCE_RESOLUTION`]) to the actual image size, using the larger of
/// width/height as the reference dimension. Use for isotropic sizes/radii; for
/// per-axis offsets scale by `width`/`height` directly (`v * dim / REFERENCE_RESOLUTION`).
pub fn scale_to_resolution(value: f32, width: u32, height: u32) -> f32 {
    value * (width.max(height) as f32 / REFERENCE_RESOLUTION)
}

/// Generates the [`Operation`] enum and its method dispatch implementations.
///
/// Each variant maps to an operation struct that provides `settings()`,
/// `create_inputs()`, `create_outputs()`, and `async fn run()`. The macro
/// generates match arms that delegate each `Operation` method call to the
/// corresponding struct's static/async methods.
#[macro_export]
macro_rules! operations {
    ( $($variant:ident($inner:ty)),* $(,)?) => {
        #[derive(Debug, Serialize, Deserialize, Clone)]
        pub enum Operation {
            $($variant,)*
        }

        impl Operation {
            pub fn settings(&self) -> NodeSettings {
                match self {
                    $(Operation::$variant => <$inner>::settings(),)*
                }
            }

            pub fn create_inputs(&self) -> Vec<Input> {
                match self {
                    $(Operation::$variant => <$inner>::create_inputs(),)*
                }
            }

            pub fn create_outputs(&self) -> Vec<Output> {
                match self {
                    $(Operation::$variant => <$inner>::create_outputs(),)*
                }
            }

            pub async fn run(&self, inputs: &mut [Input]) -> Result<$crate::operations::OperationResponse, $crate::operations::OperationError> {
                match self {
                    $(Operation::$variant => <$inner>::run(inputs).await,)*
                }
            }
        }
    };
}

operations! {
    // numbers
    OpNumberInputInteger(crate::operations::numbers::inputs::integer::OpNumberInputInteger),
    OpNumberInputDecimal(crate::operations::numbers::inputs::decimal::OpNumberInputDecimal),
    OpNumberInputPi(crate::operations::numbers::inputs::pi::OpNumberInputPi),
    OpNumberInputTau(crate::operations::numbers::inputs::tau::OpNumberInputTau),
    OpNumberInputE(crate::operations::numbers::inputs::e::OpNumberInputE),
    OpNumberInputPhi(crate::operations::numbers::inputs::phi::OpNumberInputPhi),

    OpNumberMathAdd(crate::operations::numbers::arithmetic::add::OpNumberMathAdd),
    OpNumberMathSubtract(crate::operations::numbers::arithmetic::subtract::OpNumberMathSubtract),
    OpNumberMathMultiply(crate::operations::numbers::arithmetic::multiply::OpNumberMathMultiply),
    OpNumberMathDivide(crate::operations::numbers::arithmetic::divide::OpNumberMathDivide),
    OpNumberMathDecrement(crate::operations::numbers::arithmetic::decrement::OpNumberMathDecrement),
    OpNumberMathIncrement(crate::operations::numbers::arithmetic::increment::OpNumberMathIncrement),
    OpNumberMathMax(crate::operations::numbers::arithmetic::max::OpNumberMathMax),
    OpNumberMathMin(crate::operations::numbers::arithmetic::min::OpNumberMathMin),
    OpNumberMathClamp(crate::operations::numbers::arithmetic::clamp::OpNumberMathClamp),
    OpNumberMathModulus(crate::operations::numbers::arithmetic::modulus::OpNumberMathModulus),
    OpNumberMathRound(crate::operations::numbers::arithmetic::round::OpNumberMathRound),
    OpNumberMathSign(crate::operations::numbers::arithmetic::sign::OpNumberMathSign),
    OpNumberMathNegate(crate::operations::numbers::arithmetic::negate::OpNumberMathNegate),
    OpNumberMathReciprocal(crate::operations::numbers::arithmetic::reciprocal::OpNumberMathReciprocal),
    OpNumberMathAverage(crate::operations::numbers::arithmetic::average::OpNumberMathAverage),
    OpNumberMathCeil(crate::operations::numbers::arithmetic::ceil::OpNumberMathCeil),
    OpNumberMathFloor(crate::operations::numbers::arithmetic::floor::OpNumberMathFloor),
    OpNumberMathTrunc(crate::operations::numbers::arithmetic::trunc::OpNumberMathTrunc),
    OpNumberMathFrac(crate::operations::numbers::arithmetic::frac::OpNumberMathFrac),
    OpNumberMathSnap(crate::operations::numbers::arithmetic::snap::OpNumberMathSnap),
    OpNumberMathWrap(crate::operations::numbers::arithmetic::wrap::OpNumberMathWrap),
    OpNumberMathPingPong(crate::operations::numbers::arithmetic::ping_pong::OpNumberMathPingPong),

    // interpolation
    OpNumberMathStep(crate::operations::numbers::interpolation::step::OpNumberMathStep),
    OpNumberMathSmoothstep(crate::operations::numbers::interpolation::smoothstep::OpNumberMathSmoothstep),
    OpNumberMathLerp(crate::operations::numbers::interpolation::lerp::OpNumberMathLerp),
    OpNumberMathMapRange(crate::operations::numbers::interpolation::map_range::OpNumberMathMapRange),

    // trigonometry
    OpNumberTrigSin(crate::operations::numbers::trigonometry::sin::OpNumberTrigSin),
    OpNumberTrigCos(crate::operations::numbers::trigonometry::cos::OpNumberTrigCos),
    OpNumberTrigTan(crate::operations::numbers::trigonometry::tan::OpNumberTrigTan),
    OpNumberTrigAsin(crate::operations::numbers::trigonometry::asin::OpNumberTrigAsin),
    OpNumberTrigAcos(crate::operations::numbers::trigonometry::acos::OpNumberTrigAcos),
    OpNumberTrigAtan(crate::operations::numbers::trigonometry::atan::OpNumberTrigAtan),
    OpNumberTrigAtan2(crate::operations::numbers::trigonometry::atan2::OpNumberTrigAtan2),
    OpNumberTrigSinh(crate::operations::numbers::trigonometry::sinh::OpNumberTrigSinh),
    OpNumberTrigCosh(crate::operations::numbers::trigonometry::cosh::OpNumberTrigCosh),
    OpNumberTrigTanh(crate::operations::numbers::trigonometry::tanh::OpNumberTrigTanh),
    OpNumberTrigToDegrees(crate::operations::numbers::trigonometry::to_degrees::OpNumberTrigToDegrees),
    OpNumberTrigToRadians(crate::operations::numbers::trigonometry::to_radians::OpNumberTrigToRadians),
    OpNumberTrigAsinh(crate::operations::numbers::trigonometry::asinh::OpNumberTrigAsinh),
    OpNumberTrigAcosh(crate::operations::numbers::trigonometry::acosh::OpNumberTrigAcosh),
    OpNumberTrigAtanh(crate::operations::numbers::trigonometry::atanh::OpNumberTrigAtanh),

    // random
    OpNumberRandomDecimal(crate::operations::numbers::random::random_decimal::OpNumberRandomDecimal),
    OpNumberRandomInteger(crate::operations::numbers::random::random_integer::OpNumberRandomInteger),
    OpNumberRandomGaussian(crate::operations::numbers::random::random_gaussian::OpNumberRandomGaussian),

    // algebra
    OpNumberMathAbs(crate::operations::numbers::algebra::abs::OpNumberMathAbs),
    OpNumberMathSqrt(crate::operations::numbers::algebra::sqrt::OpNumberMathSqrt),
    OpNumberMathCbrt(crate::operations::numbers::algebra::cbrt::OpNumberMathCbrt),
    OpNumberMathNthRt(crate::operations::numbers::algebra::nth_root::OpNumberMathNthRt),
    OpNumberMathPow(crate::operations::numbers::algebra::pow::OpNumberMathPow),
    OpNumberMathFactorial(crate::operations::numbers::algebra::factorial::OpNumberMathFactorial),
    OpNumberMathGcd(crate::operations::numbers::algebra::gcd::OpNumberMathGcd),
    OpNumberMathLcm(crate::operations::numbers::algebra::lcm::OpNumberMathLcm),
    OpNumberMathHypot(crate::operations::numbers::algebra::hypot::OpNumberMathHypot),
    OpNumberMathDistance2d(crate::operations::numbers::algebra::distance_2d::OpNumberMathDistance2d),

    // cast
    OpNumberCastToDecimal(crate::operations::numbers::cast::to_decimal::OpNumberCastToDecimal),
    OpNumberCastToInteger(crate::operations::numbers::cast::to_integer::OpNumberCastToInteger),

    // logarithmic
    OpNumberMathLog(crate::operations::numbers::logarithmic::log::OpNumberMathLog),
    OpNumberMathLn(crate::operations::numbers::logarithmic::ln::OpNumberMathLn),
    OpNumberMathExp(crate::operations::numbers::logarithmic::exp::OpNumberMathExp),
    OpNumberMathLog2(crate::operations::numbers::logarithmic::log2::OpNumberMathLog2),
    OpNumberMathLog10(crate::operations::numbers::logarithmic::log10::OpNumberMathLog10),

    // colors
    OpColorInputCmyk(crate::operations::colors::inputs::cmyk::OpColorInputCmyk),
    OpColorInputHsl(crate::operations::colors::inputs::hsl::OpColorInputHsla),
    OpColorInputHsv(crate::operations::colors::inputs::hsv::OpColorInputHsva),
    OpColorInputLab(crate::operations::colors::inputs::lab::OpColorInputLab),
    OpColorInputLch(crate::operations::colors::inputs::lch::OpColorInputLch),
    OpColorInputRgbLinear(crate::operations::colors::inputs::rgb_linear::OpColorInputRgbaLinear),
    OpColorInputRgb(crate::operations::colors::inputs::srgb::OpColorInputRgba),
    OpColorInputXyz(crate::operations::colors::inputs::xyz::OpColorInputXyz),
    OpColorInputYuv(crate::operations::colors::inputs::yuv::OpColorInputYuv),
    OpColorInputOklab(crate::operations::colors::inputs::oklab::OpColorInputOklab),
    OpColorInputOklch(crate::operations::colors::inputs::oklch::OpColorInputOklch),
    OpColorInputHwb(crate::operations::colors::inputs::hwb::OpColorInputHwb),
    OpColorInputYcbcr(crate::operations::colors::inputs::ycbcr::OpColorInputYcbcr),
    OpColorInputXyy(crate::operations::colors::inputs::xyy::OpColorInputXyy),

    OpColorOutputCmyk(crate::operations::colors::outputs::to_cmyk::OpColorOutputCmyk),
    OpColorOutputHsl(crate::operations::colors::outputs::to_hsl::OpColorOutputHsl),
    OpColorOutputHsv(crate::operations::colors::outputs::to_hsv::OpColorOutputHsv),
    OpColorOutputLab(crate::operations::colors::outputs::to_lab::OpColorOutputLab),
    OpColorOutputLch(crate::operations::colors::outputs::to_lch::OpColorOutputLch),
    OpColorOutputRgbLinear(crate::operations::colors::outputs::to_rgb_linear::OpColorOutputRgbLinear),
    OpColorOutputRgb(crate::operations::colors::outputs::to_srgb::OpColorOutputRgb),
    OpColorOutputXyz(crate::operations::colors::outputs::to_xyz::OpColorOutputXyz),
    OpColorOutputYuv(crate::operations::colors::outputs::to_yuv::OpColorOutputYuv),
    OpColorOutputOklab(crate::operations::colors::outputs::to_oklab::OpColorOutputOklab),
    OpColorOutputOklch(crate::operations::colors::outputs::to_oklch::OpColorOutputOklch),
    OpColorOutputHwb(crate::operations::colors::outputs::to_hwb::OpColorOutputHwb),
    OpColorOutputYcbcr(crate::operations::colors::outputs::to_ycbcr::OpColorOutputYcbcr),
    OpColorOutputXyy(crate::operations::colors::outputs::to_xyy::OpColorOutputXyy),

    OpColorBlendMode(crate::operations::colors::blend::blend_mode::OpColorBlendMode),

    OpColorSampleMostCommonColors(crate::operations::colors::sample_image::most_common_colors::OpColorSampleMostCommonColors),
    OpColorSampleSamplePixel(crate::operations::colors::sample_image::sample_pixel::OpColorSampleSamplePixel),

    OpColorCastToColor(crate::operations::colors::cast::to_color::OpColorCastToColor),

    OpColorGenerationFromHex(crate::operations::colors::generation::from_hex::OpColorGenerationFromHex),
    OpColorGenerationToHex(crate::operations::colors::generation::to_hex::OpColorGenerationToHex),
    OpColorGenerationRandomColor(crate::operations::colors::generation::random_color::OpColorGenerationRandomColor),

    OpColorManipulationInvert(crate::operations::colors::manipulation::invert::OpColorManipulationInvert),
    OpColorManipulationGrayscale(crate::operations::colors::manipulation::grayscale::OpColorManipulationGrayscale),
    OpColorManipulationAdjustHsv(crate::operations::colors::manipulation::adjust_hsv::OpColorManipulationAdjustHsv),
    OpColorManipulationClamp(crate::operations::colors::manipulation::clamp::OpColorManipulationClamp),
    OpColorManipulationSetAlpha(crate::operations::colors::manipulation::set_alpha::OpColorManipulationSetAlpha),

    OpColorAnalysisDistance(crate::operations::colors::analysis::distance::OpColorAnalysisDistance),
    OpColorAnalysisLuminance(crate::operations::colors::analysis::luminance::OpColorAnalysisLuminance),
    OpColorAnalysisContrastRatio(crate::operations::colors::analysis::contrast_ratio::OpColorAnalysisContrastRatio),
    OpColorAnalysisColorTemperature(crate::operations::colors::analysis::color_temperature::OpColorAnalysisColorTemperature),
    OpColorAnalysisDominantHue(crate::operations::colors::analysis::dominant_hue::OpColorAnalysisDominantHue),
    OpColorAnalysisHarmonyScore(crate::operations::colors::analysis::harmony_score::OpColorAnalysisHarmonyScore),
    OpColorAnalysisMixRatio(crate::operations::colors::analysis::mix_ratio::OpColorAnalysisMixRatio),

    OpColorHarmonyComplementary(crate::operations::colors::relationship::complementary::OpColorHarmonyComplementary),
    OpColorHarmonyTriadic(crate::operations::colors::relationship::triadic::OpColorHarmonyTriadic),
    OpColorHarmonyAnalogous(crate::operations::colors::relationship::analogous::OpColorHarmonyAnalogous),
    OpColorHarmonyTetradic(crate::operations::colors::relationship::tetradic::OpColorHarmonyTetradic),
    OpColorHarmonyDoubleSplitComplementary(crate::operations::colors::relationship::double_split_complementary::OpColorHarmonyDoubleSplitComplementary),
    OpColorHarmonyMonochromatic(crate::operations::colors::relationship::monochromatic::OpColorHarmonyMonochromatic),

    // image
    OpImageInputUrl(crate::operations::images::inputs::url::OpImageInputUrl),
    OpImageInputClipboard(crate::operations::images::inputs::clipboard::OpImageInputClipboard),
    OpImageInputColor(crate::operations::images::inputs::color::OpImageInputColor),
    OpImageInputFile(crate::operations::images::inputs::file::OpImageInputFile),
    OpImageInputGradient(crate::operations::images::inputs::gradient::OpImageInputGradient),
    OpImageInputText(crate::operations::images::inputs::text::OpImageInputText),
    OpImageInputConstant(crate::operations::images::inputs::constant::OpImageInputConstant),

    OpImageOutputClipboard(crate::operations::images::outputs::clipboard::OpImageOutputClipboard),
    OpImageOutputFile(crate::operations::images::outputs::file::OpImageOutputFile),
    OpImageOutputMaterial(crate::operations::images::outputs::material::OpImageOutputMaterial),

    OpImageCombineBlit(crate::operations::images::combine::blit::OpImageCombineBlit),
    OpImageCombineBlend(crate::operations::images::combine::blend::OpImageCombineBlend),
    OpImageCombineCompare(crate::operations::images::combine::compare::OpImageCombineCompare),

    OpImageTransformCrop(crate::operations::images::transform::crop::OpImageTransformCrop),
    OpImageTransformResize(crate::operations::images::transform::resize::OpImageTransformResize),
    OpImageTransformResizeExact(crate::operations::images::transform::resize_exact::OpImageTransformResizeExact),
    OpImageTransformResizeFill(crate::operations::images::transform::resize_fill::OpImageTransformResizeFill),
    OpImageTransformFlipHorizontal(crate::operations::images::transform::flip_horizontal::OpImageTransformFlipHorizontal),
    OpImageTransformFlipVertical(crate::operations::images::transform::flip_vertical::OpImageTransformFlipVertical),
    OpImageTransformRotate90(crate::operations::images::transform::rotate_90::OpImageTransformRotate90),
    OpImageTransformRotate180(crate::operations::images::transform::rotate_180::OpImageTransformRotate180),
    OpImageTransformRotate270(crate::operations::images::transform::rotate_270::OpImageTransformRotate270),
    OpImageTransformRotateAroundCenter(crate::operations::images::transform::rotate_around_center::OpImageTransformRotateAroundCenter),

    OpImageTransformWarp(crate::operations::images::transform::warp::OpImageTransformWarp),
    OpImageTransformDirectionalWarp(crate::operations::images::transform::directional_warp::OpImageTransformDirectionalWarp),
    OpImageTransformAffine(crate::operations::images::transform::transform::OpImageTransformAffine),
    OpImageTransformMakeTile(crate::operations::images::transform::make_tile::OpImageTransformMakeTile),
    OpImageTransformMirror(crate::operations::images::transform::mirror::OpImageTransformMirror),
    OpImageTransformSeamCarve(crate::operations::images::transform::seam_carve::OpImageTransformSeamCarve),
    OpImageTransformSwirl(crate::operations::images::transform::swirl::OpImageTransformSwirl),
    OpImageTransformKaleidoscope(crate::operations::images::transform::kaleidoscope::OpImageTransformKaleidoscope),
    OpImageTransformPolarCoordinates(crate::operations::images::transform::polar_coordinates::OpImageTransformPolarCoordinates),
    OpImageTransformSpherize(crate::operations::images::transform::spherize::OpImageTransformSpherize),
    OpImageTransformPerspective(crate::operations::images::transform::perspective::OpImageTransformPerspective),

    // blur
    OpImageAdjustmentBlur(crate::operations::images::blur::blur::OpImageAdjustmentBlur),
    OpImageAdjustmentContrast(crate::operations::images::adjustments::contrast::OpImageAdjustmentContrast),
    OpImageAdjustmentGrayscale(crate::operations::images::adjustments::grayscale::OpImageAdjustmentGrayscale),
    OpImageAdjustmentInvert(crate::operations::images::adjustments::invert::OpImageAdjustmentInvert),
    OpImageAdjustmentBrighten(crate::operations::images::adjustments::brighten::OpImageAdjustmentBrighten),
    OpImageAdjustmentHueRotate(crate::operations::images::adjustments::hue_rotate::OpImageAdjustmentHueRotate),
    OpImageAdjustmentUnsharpen(crate::operations::images::filter::edges::unsharpen::OpImageAdjustmentUnsharpen),
    OpImageAdjustmentLevels(crate::operations::images::adjustments::levels::OpImageAdjustmentLevels),
    OpImageAdjustmentCurves(crate::operations::images::adjustments::curves::OpImageAdjustmentCurves),
    OpImageAdjustmentGradientMap(crate::operations::images::adjustments::gradient_map::OpImageAdjustmentGradientMap),

    OpImageAdjustmentDirectionalBlur(crate::operations::images::blur::directional_blur::OpImageAdjustmentDirectionalBlur),
    OpImageAdjustmentRadialBlur(crate::operations::images::blur::radial_blur::OpImageAdjustmentRadialBlur),
    OpImageAdjustmentSlopeBlur(crate::operations::images::blur::slope_blur::OpImageAdjustmentSlopeBlur),
    OpImageAdjustmentNonUniformBlur(crate::operations::images::blur::non_uniform_blur::OpImageAdjustmentNonUniformBlur),

    // filter
    OpImageAdjustmentEdgeDetect(crate::operations::images::filter::edges::edge_detect::OpImageAdjustmentEdgeDetect),
    OpImageAdjustmentEmboss(crate::operations::images::filter::stylize::emboss::OpImageAdjustmentEmboss),
    OpImageAdjustmentSharpen(crate::operations::images::filter::edges::sharpen::OpImageAdjustmentSharpen),
    OpImageAdjustmentKuwahara(crate::operations::images::filter::stylize::kuwahara::OpImageAdjustmentKuwahara),
    OpImageAdjustmentAnisotropicKuwahara(crate::operations::images::filter::stylize::anisotropic_kuwahara::OpImageAdjustmentAnisotropicKuwahara),
    OpImageAdjustmentBilateral(crate::operations::images::filter::smoothing::bilateral::OpImageAdjustmentBilateral),
    OpImageAdjustmentSnn(crate::operations::images::filter::smoothing::snn::OpImageAdjustmentSnn),
    OpImageAdjustmentToon(crate::operations::images::filter::stylize::toon::OpImageAdjustmentToon),
    OpImageAdjustmentMedian(crate::operations::images::filter::smoothing::median::OpImageAdjustmentMedian),
    OpImageAdjustmentGuided(crate::operations::images::filter::smoothing::guided::OpImageAdjustmentGuided),
    OpImageAdjustmentDog(crate::operations::images::filter::edges::dog::OpImageAdjustmentDog),
    OpImageAdjustmentCanny(crate::operations::images::filter::edges::canny::OpImageAdjustmentCanny),
    OpImageAdjustmentErode(crate::operations::images::filter::morphology::erode::OpImageAdjustmentErode),
    OpImageAdjustmentDilate(crate::operations::images::filter::morphology::dilate::OpImageAdjustmentDilate),
    OpImageAdjustmentOpen(crate::operations::images::filter::morphology::open::OpImageAdjustmentOpen),
    OpImageAdjustmentClose(crate::operations::images::filter::morphology::close::OpImageAdjustmentClose),
    OpImageAdjustmentConvolution(crate::operations::images::filter::convolution::OpImageAdjustmentConvolution),
    OpImageAdjustmentMorphGradient(crate::operations::images::filter::morphology::morphological_gradient::OpImageAdjustmentMorphGradient),
    OpImageAdjustmentTopHat(crate::operations::images::filter::morphology::top_hat::OpImageAdjustmentTopHat),
    OpImageAdjustmentBlackHat(crate::operations::images::filter::morphology::black_hat::OpImageAdjustmentBlackHat),
    OpImageAdjustmentHighpass(crate::operations::images::filter::edges::highpass::OpImageAdjustmentHighpass),
    OpImageAdjustmentLuminanceHighpass(crate::operations::images::filter::edges::luminance_highpass::OpImageAdjustmentLuminanceHighpass),
    OpImageAdjustmentNonLocalMeans(crate::operations::images::filter::smoothing::non_local_means::OpImageAdjustmentNonLocalMeans),
    OpImageAdjustmentAnisotropicDiffusion(crate::operations::images::filter::smoothing::anisotropic_diffusion::OpImageAdjustmentAnisotropicDiffusion),
    OpImageAdjustmentOilPaint(crate::operations::images::filter::stylize::oil_paint::OpImageAdjustmentOilPaint),
    OpImageAdjustmentHalftone(crate::operations::images::filter::stylize::halftone::OpImageAdjustmentHalftone),
    OpImageAdjustmentOrderedDither(crate::operations::images::filter::dither::ordered_dither::OpImageAdjustmentOrderedDither),
    OpImageAdjustmentCrossHatch(crate::operations::images::filter::stylize::cross_hatch::OpImageAdjustmentCrossHatch),
    OpImageAdjustmentFloydSteinberg(crate::operations::images::filter::dither::floyd_steinberg::OpImageAdjustmentFloydSteinberg),
    OpImageAdjustmentAscii(crate::operations::images::filter::stylize::ascii::OpImageAdjustmentAscii),
    OpImageAdjustmentPosterize(crate::operations::images::adjustments::posterize::OpImageAdjustmentPosterize),
    OpImageAdjustmentDither(crate::operations::images::adjustments::dither::OpImageAdjustmentDither),
    OpImageAdjustmentHistogramScan(crate::operations::images::adjustments::histogram_scan::OpImageAdjustmentHistogramScan),
    OpImageAdjustmentHistogramRange(crate::operations::images::adjustments::histogram_range::OpImageAdjustmentHistogramRange),
    OpImageAdjustmentHistogramSelect(crate::operations::images::adjustments::histogram_select::OpImageAdjustmentHistogramSelect),
    OpImageAdjustmentAutoLevels(crate::operations::images::adjustments::auto_levels::OpImageAdjustmentAutoLevels),
    OpImageAdjustmentColorMatch(crate::operations::images::adjustments::color_match::OpImageAdjustmentColorMatch),
    OpImageAdjustmentGradientDynamic(crate::operations::images::adjustments::gradient_dynamic::OpImageAdjustmentGradientDynamic),
    OpImageAdjustmentDistance(crate::operations::images::adjustments::distance::OpImageAdjustmentDistance),
    OpImageAdjustmentColorToMask(crate::operations::images::adjustments::color_to_mask::OpImageAdjustmentColorToMask),
    OpImageAdjustmentReplaceColor(crate::operations::images::adjustments::replace_color::OpImageAdjustmentReplaceColor),
    OpImageAdjustmentHsl(crate::operations::images::adjustments::hsl::OpImageAdjustmentHsl),
    OpImageAdjustmentFrequencySplit(crate::operations::images::adjustments::frequency_split::OpImageAdjustmentFrequencySplit),
    OpImageAdjustmentOutline(crate::operations::images::filter::morphology::outline::OpImageAdjustmentOutline),
    OpImageAdjustmentPixelate(crate::operations::images::filter::stylize::pixelate::OpImageAdjustmentPixelate),
    OpImageAdjustmentVectorMorphology(crate::operations::images::filter::morphology::vector_morphology::OpImageAdjustmentVectorMorphology),
    OpImageAdjustmentSaturation(crate::operations::images::adjustments::saturation::OpImageAdjustmentSaturation),
    OpImageAdjustmentThreshold(crate::operations::images::adjustments::threshold::OpImageAdjustmentThreshold),
    OpImageAdjustmentVignette(crate::operations::images::adjustments::vignette::OpImageAdjustmentVignette),
    OpImageAdjustmentWhiteBalance(crate::operations::images::adjustments::white_balance::OpImageAdjustmentWhiteBalance),
    OpImageAdjustmentColorBalance(crate::operations::images::adjustments::color_balance::OpImageAdjustmentColorBalance),
    OpImageAdjustmentSelectiveColor(crate::operations::images::adjustments::selective_color::OpImageAdjustmentSelectiveColor),

    // mask fx
    OpImageFxDropShadow(crate::operations::images::fx::drop_shadow::OpImageFxDropShadow),
    OpImageFxOuterGlow(crate::operations::images::fx::outer_glow::OpImageFxOuterGlow),
    OpImageFxInnerGlow(crate::operations::images::fx::inner_glow::OpImageFxInnerGlow),

    OpImageChannelSplit(crate::operations::images::channels::split::OpImageChannelSplit),
    OpImageChannelMerge(crate::operations::images::channels::merge::OpImageChannelMerge),
    OpImageChannelShuffle(crate::operations::images::channels::shuffle::OpImageChannelShuffle),
    OpImageChannelSelect(crate::operations::images::channels::select::OpImageChannelSelect),
    OpImageChannelMixer(crate::operations::images::channels::mixer::OpImageChannelMixer),

    OpImageNoisePerlin(crate::operations::images::noise::basic::perlin::OpImageNoisePerlin),
    OpImageNoiseWorleyDistance(crate::operations::images::noise::cellular::worley_distance::OpImageNoiseWorleyDistance),
    OpImageNoiseWorleyValue(crate::operations::images::noise::cellular::worley_value::OpImageNoiseWorleyValue),
    OpImageNoiseHeterogenousMultifractalNoise(crate::operations::images::noise::fractal::basic_multifractal::OpImageNoiseHeterogenousMultifractalNoise),
    OpImageNoiseBillow(crate::operations::images::noise::fractal::billow::OpImageNoiseBillow),
    OpImageNoiseCylinders(crate::operations::images::noise::structural::cylinders::OpImageNoiseCylinders),
    OpImageNoiseDomainWarpFbm(crate::operations::images::noise::fractal::domain_warp_fbm::OpImageNoiseDomainWarpFbm),
    OpImageNoiseFbm(crate::operations::images::noise::fractal::fbm::OpImageNoiseFbm),
    OpImageNoiseHybridMultifractalNoise(crate::operations::images::noise::fractal::hybrid_multifractal::OpImageNoiseHybridMultifractalNoise),
    OpImageNoiseOpenSimplex(crate::operations::images::noise::basic::open_simplex::OpImageNoiseOpenSimplex),
    OpImageNoiseSuperSimplex(crate::operations::images::noise::basic::super_simplex::OpImageNoiseSuperSimplex),
    OpImageNoiseRidgedMultifractalNoise(crate::operations::images::noise::fractal::ridged_multifractal::OpImageNoiseRidgedMultifractalNoise),
    OpImageNoiseValue(crate::operations::images::noise::basic::value::OpImageNoiseValue),
    OpImageNoiseVoronoiCrack(crate::operations::images::noise::cellular::voronoi_crack::OpImageNoiseVoronoiCrack),
    OpImageNoiseVoronoise(crate::operations::images::noise::cellular::voronoise::OpImageNoiseVoronoise),
    OpImageNoiseReactionDiffusion(crate::operations::images::noise::process::reaction_diffusion::OpImageNoiseReactionDiffusion),
    OpImageNoiseErosion(crate::operations::images::noise::process::erosion::OpImageNoiseErosion),
    OpImageNoiseGabor(crate::operations::images::noise::basic::gabor::OpImageNoiseGabor),
    OpImageNoiseGaussian(crate::operations::images::noise::basic::gaussian::OpImageNoiseGaussian),
    OpImageNoiseCrystal(crate::operations::images::noise::cellular::crystal::OpImageNoiseCrystal),
    OpImageNoiseClouds(crate::operations::images::noise::fractal::clouds::OpImageNoiseClouds),
    OpImageNoisePlasma(crate::operations::images::noise::fractal::plasma::OpImageNoisePlasma),
    OpImageNoiseAnisotropic(crate::operations::images::noise::basic::anisotropic::OpImageNoiseAnisotropic),
    OpImageNoiseDirt(crate::operations::images::noise::grunge::dirt::OpImageNoiseDirt),
    OpImageNoiseWave(crate::operations::images::noise::structural::wave::OpImageNoiseWave),
    OpImageNoiseBlue(crate::operations::images::noise::basic::blue_noise::OpImageNoiseBlue),
    OpImageNoiseCurl(crate::operations::images::noise::fractal::curl::OpImageNoiseCurl),
    OpImageNoiseCheckerboard(crate::operations::images::noise::structural::checkerboard::OpImageNoiseCheckerboard),
    OpImageNoiseScratches(crate::operations::images::noise::grunge::scratches::OpImageNoiseScratches),
    OpImageNoiseFibers(crate::operations::images::noise::grunge::fibers::OpImageNoiseFibers),
    OpImageNoiseCraters(crate::operations::images::noise::cellular::craters::OpImageNoiseCraters),
    OpImageNoiseScales(crate::operations::images::noise::cellular::scales::OpImageNoiseScales),
    OpImageNoiseTruchet(crate::operations::images::noise::structural::truchet::OpImageNoiseTruchet),
    OpImageNoisePhasor(crate::operations::images::noise::basic::phasor::OpImageNoisePhasor),
    OpImageNoiseFlow(crate::operations::images::noise::fractal::flow::OpImageNoiseFlow),
    OpImageNoiseFaultTerrain(crate::operations::images::noise::process::fault_terrain::OpImageNoiseFaultTerrain),
    OpImageNoiseLeaks(crate::operations::images::noise::grunge::leaks::OpImageNoiseLeaks),
    OpImageNoiseStains(crate::operations::images::noise::grunge::stains::OpImageNoiseStains),
    OpImageNoisePeeling(crate::operations::images::noise::grunge::peeling::OpImageNoisePeeling),
    OpImageNoiseSmear(crate::operations::images::noise::grunge::smear::OpImageNoiseSmear),
    OpImageNoiseGrowth(crate::operations::images::noise::grunge::growth::OpImageNoiseGrowth),
    OpImageNoiseCaustics(crate::operations::images::noise::process::caustics::OpImageNoiseCaustics),
    OpImageNoiseVeins(crate::operations::images::noise::structural::veins::OpImageNoiseVeins),
    OpImageNoiseWarpedRings(crate::operations::images::noise::structural::warped_rings::OpImageNoiseWarpedRings),
    OpImageNoiseLightning(crate::operations::images::noise::process::lightning::OpImageNoiseLightning),

    // simulation
    OpImageSimulationHydraulicErosion(crate::operations::images::simulation::hydraulic_erosion::OpImageSimulationHydraulicErosion),

    // shapes
    OpImageShapeRectangle(crate::operations::images::shapes::rectangle::OpImageShapeRectangle),
    OpImageShapeEllipse(crate::operations::images::shapes::ellipse::OpImageShapeEllipse),
    OpImageShapePolygon(crate::operations::images::shapes::polygon::OpImageShapePolygon),
    OpImageShapeStar(crate::operations::images::shapes::star::OpImageShapeStar),
    OpImageShapeLine(crate::operations::images::shapes::line::OpImageShapeLine),
    OpImageShapeParaboloid(crate::operations::images::shapes::paraboloid::OpImageShapeParaboloid),
    OpImageShapePyramid(crate::operations::images::shapes::pyramid::OpImageShapePyramid),
    OpImageShapeCone(crate::operations::images::shapes::cone::OpImageShapeCone),
    OpImageShapesCircle(crate::operations::images::shapes::circle::OpImageShapesCircle),

    // patterns
    OpImagePatternBrick(crate::operations::images::patterns::brick::OpImagePatternBrick),
    OpImagePatternHexagonal(crate::operations::images::patterns::hexagonal::OpImagePatternHexagonal),
    OpImagePatternWeave(crate::operations::images::patterns::weave::OpImagePatternWeave),
    OpImagePatternTileSampler(crate::operations::images::patterns::tile_sampler::OpImagePatternTileSampler),
    OpImagePatternFloodFill(crate::operations::images::patterns::flood_fill::OpImagePatternFloodFill),
    OpImagePatternFloodFillMapper(crate::operations::images::patterns::flood_fill_mapper::OpImagePatternFloodFillMapper),
    OpImagePatternSplatter(crate::operations::images::patterns::splatter::OpImagePatternSplatter),
    OpImagePatternTileGenerator(crate::operations::images::patterns::tile_generator::OpImagePatternTileGenerator),

    // pbr
    OpImagePbrNormalFromHeight(crate::operations::images::pbr::normal_from_height::OpImagePbrNormalFromHeight),
    OpImagePbrAoFromHeight(crate::operations::images::pbr::ao_from_height::OpImagePbrAoFromHeight),
    OpImagePbrCurvature(crate::operations::images::pbr::curvature::OpImagePbrCurvature),
    OpImagePbrHeightBlend(crate::operations::images::pbr::height_blend::OpImagePbrHeightBlend),
    OpImagePbrNormalCombine(crate::operations::images::pbr::normal_combine::OpImagePbrNormalCombine),
    OpImagePbrNormalBlend(crate::operations::images::pbr::normal_blend::OpImagePbrNormalBlend),
    OpImagePbrNormalInvert(crate::operations::images::pbr::normal_invert::OpImagePbrNormalInvert),
    OpImagePbrBevel(crate::operations::images::pbr::bevel::OpImagePbrBevel),
    OpImagePbrNormalToHeight(crate::operations::images::pbr::normal_to_height::OpImagePbrNormalToHeight),

    OpImageCastToImage(crate::operations::images::cast::to_image::OpImageCastToImage),

    // logic
    OpLogicInputBool(crate::operations::logic::inputs::bool_input::OpLogicInputBool),

    OpLogicCompareEqual(crate::operations::logic::comparison::equal::OpLogicCompareEqual),
    OpLogicCompareNotEqual(crate::operations::logic::comparison::not_equal::OpLogicCompareNotEqual),
    OpLogicCompareApproxEqual(crate::operations::logic::comparison::approx_equal::OpLogicCompareApproxEqual),
    OpLogicCompareInRange(crate::operations::logic::comparison::in_range::OpLogicCompareInRange),
    OpLogicCompareLessThan(crate::operations::logic::comparison::less_than::OpLogicCompareLessThan),
    OpLogicCompareLessEqual(crate::operations::logic::comparison::less_equal::OpLogicCompareLessEqual),
    OpLogicCompareGreaterThan(crate::operations::logic::comparison::greater_than::OpLogicCompareGreaterThan),
    OpLogicCompareGreaterEqual(crate::operations::logic::comparison::greater_equal::OpLogicCompareGreaterEqual),

    OpLogicBoolAnd(crate::operations::logic::boolean::and::OpLogicBoolAnd),
    OpLogicBoolOr(crate::operations::logic::boolean::or::OpLogicBoolOr),
    OpLogicBoolNot(crate::operations::logic::boolean::not::OpLogicBoolNot),
    OpLogicBoolXor(crate::operations::logic::boolean::xor::OpLogicBoolXor),
    OpLogicBoolXnor(crate::operations::logic::boolean::xnor::OpLogicBoolXnor),
    OpLogicBoolNand(crate::operations::logic::boolean::nand::OpLogicBoolNand),
    OpLogicBoolNor(crate::operations::logic::boolean::nor::OpLogicBoolNor),

    OpLogicFlowSelect(crate::operations::logic::flow::select::OpLogicFlowSelect),

    // logic ← text (predicates)
    OpLogicTextContains(crate::operations::logic::text::contains::OpLogicTextContains),
    OpLogicTextStartsWith(crate::operations::logic::text::starts_with::OpLogicTextStartsWith),
    OpLogicTextEndsWith(crate::operations::logic::text::ends_with::OpLogicTextEndsWith),
    OpLogicTextIsEmpty(crate::operations::logic::text::is_empty::OpLogicTextIsEmpty),
    OpLogicTextEqualsIgnoreCase(crate::operations::logic::text::equals_ignore_case::OpLogicTextEqualsIgnoreCase),

    // text
    OpTextInput(crate::operations::text::inputs::text_input::OpTextInput),
    OpTextAppend(crate::operations::text::manipulation::append::OpTextAppend),
    OpTextLength(crate::operations::text::manipulation::length::OpTextLength),
    OpTextToUppercase(crate::operations::text::manipulation::to_uppercase::OpTextToUppercase),
    OpTextToLowercase(crate::operations::text::manipulation::to_lowercase::OpTextToLowercase),
    OpTextToString(crate::operations::text::manipulation::to_string::OpTextToString),
    OpTextJoin(crate::operations::text::manipulation::join::OpTextJoin),
    OpTextReplace(crate::operations::text::manipulation::replace::OpTextReplace),
    OpTextSubstring(crate::operations::text::manipulation::substring::OpTextSubstring),
    OpTextSplit(crate::operations::text::manipulation::split::OpTextSplit),
    OpTextTrim(crate::operations::text::manipulation::trim::OpTextTrim),
    OpTextPad(crate::operations::text::manipulation::pad::OpTextPad),
    OpTextRepeat(crate::operations::text::manipulation::repeat::OpTextRepeat),
    OpTextReverse(crate::operations::text::manipulation::reverse::OpTextReverse),
    OpTextTemplate(crate::operations::text::manipulation::template::OpTextTemplate),
    OpTextTitleCase(crate::operations::text::manipulation::title_case::OpTextTitleCase),
    OpTextFormatNumber(crate::operations::text::manipulation::format_number::OpTextFormatNumber),

    // text encoding
    OpTextBase64Encode(crate::operations::text::encoding::base64_encode::OpTextBase64Encode),
    OpTextBase64Decode(crate::operations::text::encoding::base64_decode::OpTextBase64Decode),
    OpTextUrlEncode(crate::operations::text::encoding::url_encode::OpTextUrlEncode),
    OpTextUrlDecode(crate::operations::text::encoding::url_decode::OpTextUrlDecode),

    // text ← image
    OpTextImageAsciiArt(crate::operations::text::image::ascii_art::OpTextImageAsciiArt),
    OpTextImageDataUri(crate::operations::text::image::data_uri::OpTextImageDataUri),
    OpTextImageInfo(crate::operations::text::image::image_info::OpTextImageInfo),
    OpTextImagePaletteHex(crate::operations::text::image::palette_hex::OpTextImagePaletteHex),
    OpTextImageHash(crate::operations::text::image::image_hash::OpTextImageHash),

    // bitwise
    OpNumberBitwiseAnd(crate::operations::numbers::bitwise::bit_and::OpNumberBitwiseAnd),
    OpNumberBitwiseOr(crate::operations::numbers::bitwise::bit_or::OpNumberBitwiseOr),
    OpNumberBitwiseXor(crate::operations::numbers::bitwise::bit_xor::OpNumberBitwiseXor),
    OpNumberBitwiseNot(crate::operations::numbers::bitwise::bit_not::OpNumberBitwiseNot),
    OpNumberBitwiseShiftLeft(crate::operations::numbers::bitwise::bit_shift_left::OpNumberBitwiseShiftLeft),
    OpNumberBitwiseShiftRight(crate::operations::numbers::bitwise::bit_shift_right::OpNumberBitwiseShiftRight),

    // image (image → number measurements)
    OpNumberImageDimensions(crate::operations::numbers::image::dimensions::OpNumberImageDimensions),
    OpNumberImageMean(crate::operations::numbers::image::mean::OpNumberImageMean),
    OpNumberImageMinMax(crate::operations::numbers::image::min_max::OpNumberImageMinMax),
    OpNumberImageMedian(crate::operations::numbers::image::median::OpNumberImageMedian),
    OpNumberImagePercentile(crate::operations::numbers::image::percentile::OpNumberImagePercentile),
    OpNumberImageStdDev(crate::operations::numbers::image::std_dev::OpNumberImageStdDev),
    OpNumberImageEntropy(crate::operations::numbers::image::entropy::OpNumberImageEntropy),
    OpNumberImageSkewness(crate::operations::numbers::image::skewness::OpNumberImageSkewness),
    OpNumberImageKurtosis(crate::operations::numbers::image::kurtosis::OpNumberImageKurtosis),
    OpNumberImageBoundingBox(crate::operations::numbers::image::bounding_box::OpNumberImageBoundingBox),
    OpNumberImageCentroid(crate::operations::numbers::image::centroid::OpNumberImageCentroid),
    OpNumberImageCoverage(crate::operations::numbers::image::coverage::OpNumberImageCoverage),
    OpNumberImageSharpness(crate::operations::numbers::image::sharpness::OpNumberImageSharpness),
    OpNumberImageEdgeDensity(crate::operations::numbers::image::edge_density::OpNumberImageEdgeDensity),
    OpNumberImageUniqueColors(crate::operations::numbers::image::unique_colors::OpNumberImageUniqueColors),
    OpNumberImageAverageHue(crate::operations::numbers::image::average_hue::OpNumberImageAverageHue),
    OpNumberImageDifference(crate::operations::numbers::image::image_difference::OpNumberImageDifference),
    OpNumberImagePerceptualHash(crate::operations::numbers::image::perceptual_hash::OpNumberImagePerceptualHash),

    // numbers ← text (measurements / parsing)
    OpNumberTextParseDecimal(crate::operations::numbers::text::parse_decimal::OpNumberTextParseDecimal),
    OpNumberTextParseInteger(crate::operations::numbers::text::parse_integer::OpNumberTextParseInteger),
    OpNumberTextWordCount(crate::operations::numbers::text::word_count::OpNumberTextWordCount),
    OpNumberTextLineCount(crate::operations::numbers::text::line_count::OpNumberTextLineCount),
    OpNumberTextByteLength(crate::operations::numbers::text::byte_length::OpNumberTextByteLength),
    OpNumberTextIndexOf(crate::operations::numbers::text::index_of::OpNumberTextIndexOf),
    OpNumberTextCountOccurrences(crate::operations::numbers::text::count_occurrences::OpNumberTextCountOccurrences),
}

/// Returns the full hierarchical menu of available operations.
///
/// This defines the structure of the "Add Node" context menu in the GUI,
/// organized into top-level categories (numbers, colors, images, logic)
/// with nested subcategories.
pub fn operation_list() -> Vec<OperationListItem> {
    let mut list = vec![
        OperationListItem::Category { name: "numbers".to_string(), operation_list_items: vec![
            OperationListItem::Category { name: "input".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberInputDecimal },
                OperationListItem::Operation { operation: Operation::OpNumberInputInteger },
                OperationListItem::Operation { operation: Operation::OpNumberInputPi },
                OperationListItem::Operation { operation: Operation::OpNumberInputTau },
                OperationListItem::Operation { operation: Operation::OpNumberInputE },
                OperationListItem::Operation { operation: Operation::OpNumberInputPhi },
            ]},
            OperationListItem::Category { name: "arithmetic".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberMathAdd },
                OperationListItem::Operation { operation: Operation::OpNumberMathSubtract },
                OperationListItem::Operation { operation: Operation::OpNumberMathMultiply },
                OperationListItem::Operation { operation: Operation::OpNumberMathDivide },
                OperationListItem::Operation { operation: Operation::OpNumberMathIncrement },
                OperationListItem::Operation { operation: Operation::OpNumberMathDecrement },
                OperationListItem::Operation { operation: Operation::OpNumberMathMax },
                OperationListItem::Operation { operation: Operation::OpNumberMathMin },
                OperationListItem::Operation { operation: Operation::OpNumberMathClamp },
                OperationListItem::Operation { operation: Operation::OpNumberMathModulus },
                OperationListItem::Operation { operation: Operation::OpNumberMathRound },
                OperationListItem::Operation { operation: Operation::OpNumberMathSign },
                OperationListItem::Operation { operation: Operation::OpNumberMathNegate },
                OperationListItem::Operation { operation: Operation::OpNumberMathReciprocal },
                OperationListItem::Operation { operation: Operation::OpNumberMathAverage },
                OperationListItem::Operation { operation: Operation::OpNumberMathCeil },
                OperationListItem::Operation { operation: Operation::OpNumberMathFloor },
                OperationListItem::Operation { operation: Operation::OpNumberMathTrunc },
                OperationListItem::Operation { operation: Operation::OpNumberMathFrac },
                OperationListItem::Operation { operation: Operation::OpNumberMathSnap },
                OperationListItem::Operation { operation: Operation::OpNumberMathWrap },
                OperationListItem::Operation { operation: Operation::OpNumberMathPingPong },
            ]},
            OperationListItem::Category { name: "interpolation".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberMathLerp },
                OperationListItem::Operation { operation: Operation::OpNumberMathSmoothstep },
                OperationListItem::Operation { operation: Operation::OpNumberMathStep },
                OperationListItem::Operation { operation: Operation::OpNumberMathMapRange },
            ]},
            OperationListItem::Category { name: "trigonometry".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberTrigSin },
                OperationListItem::Operation { operation: Operation::OpNumberTrigCos },
                OperationListItem::Operation { operation: Operation::OpNumberTrigTan },
                OperationListItem::Operation { operation: Operation::OpNumberTrigAsin },
                OperationListItem::Operation { operation: Operation::OpNumberTrigAcos },
                OperationListItem::Operation { operation: Operation::OpNumberTrigAtan },
                OperationListItem::Operation { operation: Operation::OpNumberTrigAtan2 },
                OperationListItem::Operation { operation: Operation::OpNumberTrigSinh },
                OperationListItem::Operation { operation: Operation::OpNumberTrigCosh },
                OperationListItem::Operation { operation: Operation::OpNumberTrigTanh },
                OperationListItem::Operation { operation: Operation::OpNumberTrigToDegrees },
                OperationListItem::Operation { operation: Operation::OpNumberTrigToRadians },
                OperationListItem::Operation { operation: Operation::OpNumberTrigAsinh },
                OperationListItem::Operation { operation: Operation::OpNumberTrigAcosh },
                OperationListItem::Operation { operation: Operation::OpNumberTrigAtanh },
            ]},
            OperationListItem::Category { name: "algebraic".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberMathAbs },
                OperationListItem::Operation { operation: Operation::OpNumberMathSqrt },
                OperationListItem::Operation { operation: Operation::OpNumberMathCbrt },
                OperationListItem::Operation { operation: Operation::OpNumberMathNthRt },
                OperationListItem::Operation { operation: Operation::OpNumberMathPow },
                OperationListItem::Operation { operation: Operation::OpNumberMathFactorial },
                OperationListItem::Operation { operation: Operation::OpNumberMathGcd },
                OperationListItem::Operation { operation: Operation::OpNumberMathLcm },
                OperationListItem::Operation { operation: Operation::OpNumberMathHypot },
                OperationListItem::Operation { operation: Operation::OpNumberMathDistance2d },
            ]},
            OperationListItem::Category { name: "cast".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberCastToDecimal },
                OperationListItem::Operation { operation: Operation::OpNumberCastToInteger },
            ]},
            OperationListItem::Category { name: "logarithmic".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberMathLog },
                OperationListItem::Operation { operation: Operation::OpNumberMathLn },
                OperationListItem::Operation { operation: Operation::OpNumberMathExp },
                OperationListItem::Operation { operation: Operation::OpNumberMathLog2 },
                OperationListItem::Operation { operation: Operation::OpNumberMathLog10 },
            ]},
            OperationListItem::Category { name: "random".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberRandomDecimal },
                OperationListItem::Operation { operation: Operation::OpNumberRandomInteger },
                OperationListItem::Operation { operation: Operation::OpNumberRandomGaussian },
            ]},
            OperationListItem::Category { name: "bitwise".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberBitwiseAnd },
                OperationListItem::Operation { operation: Operation::OpNumberBitwiseOr },
                OperationListItem::Operation { operation: Operation::OpNumberBitwiseXor },
                OperationListItem::Operation { operation: Operation::OpNumberBitwiseNot },
                OperationListItem::Operation { operation: Operation::OpNumberBitwiseShiftLeft },
                OperationListItem::Operation { operation: Operation::OpNumberBitwiseShiftRight },
            ]},
            OperationListItem::Category { name: "image".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberImageDimensions },
                OperationListItem::Operation { operation: Operation::OpNumberImageMean },
                OperationListItem::Operation { operation: Operation::OpNumberImageMinMax },
                OperationListItem::Operation { operation: Operation::OpNumberImageMedian },
                OperationListItem::Operation { operation: Operation::OpNumberImagePercentile },
                OperationListItem::Operation { operation: Operation::OpNumberImageStdDev },
                OperationListItem::Operation { operation: Operation::OpNumberImageEntropy },
                OperationListItem::Operation { operation: Operation::OpNumberImageSkewness },
                OperationListItem::Operation { operation: Operation::OpNumberImageKurtosis },
                OperationListItem::Operation { operation: Operation::OpNumberImageBoundingBox },
                OperationListItem::Operation { operation: Operation::OpNumberImageCentroid },
                OperationListItem::Operation { operation: Operation::OpNumberImageCoverage },
                OperationListItem::Operation { operation: Operation::OpNumberImageSharpness },
                OperationListItem::Operation { operation: Operation::OpNumberImageEdgeDensity },
                OperationListItem::Operation { operation: Operation::OpNumberImageUniqueColors },
                OperationListItem::Operation { operation: Operation::OpNumberImageAverageHue },
                OperationListItem::Operation { operation: Operation::OpNumberImageDifference },
                OperationListItem::Operation { operation: Operation::OpNumberImagePerceptualHash },
            ]},
            OperationListItem::Category { name: "text".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberTextParseDecimal },
                OperationListItem::Operation { operation: Operation::OpNumberTextParseInteger },
                OperationListItem::Operation { operation: Operation::OpNumberTextWordCount },
                OperationListItem::Operation { operation: Operation::OpNumberTextLineCount },
                OperationListItem::Operation { operation: Operation::OpNumberTextByteLength },
                OperationListItem::Operation { operation: Operation::OpNumberTextIndexOf },
                OperationListItem::Operation { operation: Operation::OpNumberTextCountOccurrences },
            ]},
        ]},
        OperationListItem::Category { name: "colors".to_string(), operation_list_items: vec![
            OperationListItem::Category { name: "input".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpColorInputCmyk },
                OperationListItem::Operation { operation: Operation::OpColorInputHsl },
                OperationListItem::Operation { operation: Operation::OpColorInputHsv },
                OperationListItem::Operation { operation: Operation::OpColorInputLab },
                OperationListItem::Operation { operation: Operation::OpColorInputLch },
                OperationListItem::Operation { operation: Operation::OpColorInputRgb },
                OperationListItem::Operation { operation: Operation::OpColorInputRgbLinear },
                OperationListItem::Operation { operation: Operation::OpColorInputXyz },
                OperationListItem::Operation { operation: Operation::OpColorInputYuv },
                OperationListItem::Operation { operation: Operation::OpColorInputOklab },
                OperationListItem::Operation { operation: Operation::OpColorInputOklch },
                OperationListItem::Operation { operation: Operation::OpColorInputHwb },
                OperationListItem::Operation { operation: Operation::OpColorInputYcbcr },
                OperationListItem::Operation { operation: Operation::OpColorInputXyy },
            ]},
            OperationListItem::Category { name: "output".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpColorOutputCmyk },
                OperationListItem::Operation { operation: Operation::OpColorOutputHsl },
                OperationListItem::Operation { operation: Operation::OpColorOutputHsv },
                OperationListItem::Operation { operation: Operation::OpColorOutputLab },
                OperationListItem::Operation { operation: Operation::OpColorOutputLch },
                OperationListItem::Operation { operation: Operation::OpColorOutputRgb },
                OperationListItem::Operation { operation: Operation::OpColorOutputRgbLinear },
                OperationListItem::Operation { operation: Operation::OpColorOutputXyz },
                OperationListItem::Operation { operation: Operation::OpColorOutputYuv },
                OperationListItem::Operation { operation: Operation::OpColorOutputOklab },
                OperationListItem::Operation { operation: Operation::OpColorOutputOklch },
                OperationListItem::Operation { operation: Operation::OpColorOutputHwb },
                OperationListItem::Operation { operation: Operation::OpColorOutputYcbcr },
                OperationListItem::Operation { operation: Operation::OpColorOutputXyy },
            ]},
            OperationListItem::Category { name: "analysis".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpColorSampleMostCommonColors },
                OperationListItem::Operation { operation: Operation::OpColorSampleSamplePixel },
                OperationListItem::Operation { operation: Operation::OpColorAnalysisDistance },
                OperationListItem::Operation { operation: Operation::OpColorAnalysisLuminance },
                OperationListItem::Operation { operation: Operation::OpColorAnalysisContrastRatio },
                OperationListItem::Operation { operation: Operation::OpColorAnalysisColorTemperature },
                OperationListItem::Operation { operation: Operation::OpColorAnalysisDominantHue },
                OperationListItem::Operation { operation: Operation::OpColorAnalysisHarmonyScore },
                OperationListItem::Operation { operation: Operation::OpColorAnalysisMixRatio },
            ]},
            OperationListItem::Category { name: "generation".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpColorGenerationFromHex },
                OperationListItem::Operation { operation: Operation::OpColorGenerationToHex },
                OperationListItem::Operation { operation: Operation::OpColorGenerationRandomColor },
                OperationListItem::Operation { operation: Operation::OpColorCastToColor },
            ]},
            OperationListItem::Category { name: "manipulation".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpColorManipulationInvert },
                OperationListItem::Operation { operation: Operation::OpColorManipulationGrayscale },
                OperationListItem::Operation { operation: Operation::OpColorManipulationAdjustHsv },
                OperationListItem::Operation { operation: Operation::OpColorManipulationClamp },
                OperationListItem::Operation { operation: Operation::OpColorManipulationSetAlpha },
                OperationListItem::Operation { operation: Operation::OpColorBlendMode },
            ]},
            OperationListItem::Category { name: "harmony".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpColorHarmonyComplementary },
                OperationListItem::Operation { operation: Operation::OpColorHarmonyTriadic },
                OperationListItem::Operation { operation: Operation::OpColorHarmonyAnalogous },
                OperationListItem::Operation { operation: Operation::OpColorHarmonyTetradic },
                OperationListItem::Operation { operation: Operation::OpColorHarmonyDoubleSplitComplementary },
                OperationListItem::Operation { operation: Operation::OpColorHarmonyMonochromatic },
            ]},
        ]},
        OperationListItem::Category { name: "images".to_string(), operation_list_items: vec![
            OperationListItem::Category { name: "input".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageInputFile },
                OperationListItem::Operation { operation: Operation::OpImageInputUrl },
                OperationListItem::Operation { operation: Operation::OpImageInputClipboard },
                OperationListItem::Operation { operation: Operation::OpImageInputColor },
                OperationListItem::Operation { operation: Operation::OpImageInputGradient },
                OperationListItem::Operation { operation: Operation::OpImageInputText },
                OperationListItem::Operation { operation: Operation::OpImageInputConstant },
            ]},
            OperationListItem::Category { name: "output".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageOutputFile },
                OperationListItem::Operation { operation: Operation::OpImageOutputClipboard },
                OperationListItem::Operation { operation: Operation::OpImageOutputMaterial },
            ]},
            OperationListItem::Category { name: "combine".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageCombineBlit },
                OperationListItem::Operation { operation: Operation::OpImageCombineBlend },
                OperationListItem::Operation { operation: Operation::OpImageCombineCompare },
            ]},
            OperationListItem::Category { name: "transform".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageTransformAffine },
                OperationListItem::Operation { operation: Operation::OpImageTransformCrop },
                OperationListItem::Operation { operation: Operation::OpImageTransformResize },
                OperationListItem::Operation { operation: Operation::OpImageTransformResizeExact },
                OperationListItem::Operation { operation: Operation::OpImageTransformResizeFill },
                OperationListItem::Operation { operation: Operation::OpImageTransformFlipHorizontal },
                OperationListItem::Operation { operation: Operation::OpImageTransformFlipVertical },
                OperationListItem::Operation { operation: Operation::OpImageTransformRotate90 },
                OperationListItem::Operation { operation: Operation::OpImageTransformRotate180 },
                OperationListItem::Operation { operation: Operation::OpImageTransformRotate270 },
                OperationListItem::Operation { operation: Operation::OpImageTransformRotateAroundCenter },
                OperationListItem::Operation { operation: Operation::OpImageTransformWarp },
                OperationListItem::Operation { operation: Operation::OpImageTransformDirectionalWarp },
                OperationListItem::Operation { operation: Operation::OpImageTransformMakeTile },
                OperationListItem::Operation { operation: Operation::OpImageTransformMirror },
                OperationListItem::Operation { operation: Operation::OpImageTransformSeamCarve },
                OperationListItem::Operation { operation: Operation::OpImageTransformSwirl },
                OperationListItem::Operation { operation: Operation::OpImageTransformKaleidoscope },
                OperationListItem::Operation { operation: Operation::OpImageTransformPolarCoordinates },
                OperationListItem::Operation { operation: Operation::OpImageTransformSpherize },
                OperationListItem::Operation { operation: Operation::OpImageTransformPerspective },
            ]},
            OperationListItem::Category { name: "adjustments".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentContrast },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentGrayscale },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentInvert },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentBrighten },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentSaturation },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentHueRotate },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentThreshold },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentVignette },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentWhiteBalance },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentColorBalance },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentSelectiveColor },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentLevels },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentAutoLevels },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentCurves },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentGradientMap },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentGradientDynamic },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentColorMatch },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentPosterize },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentDither },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentHistogramScan },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentHistogramRange },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentHistogramSelect },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentHsl },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentColorToMask },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentReplaceColor },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentFrequencySplit },
            ]},
            OperationListItem::Category { name: "blur".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentBlur },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentDirectionalBlur },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentRadialBlur },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentSlopeBlur },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentNonUniformBlur },
            ]},
            OperationListItem::Category { name: "filter".to_string(), operation_list_items: vec![
                OperationListItem::Category { name: "edges".to_string(), operation_list_items: vec![
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentEdgeDetect },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentCanny },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentDog },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentSharpen },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentUnsharpen },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentHighpass },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentLuminanceHighpass },
                ]},
                OperationListItem::Category { name: "smoothing".to_string(), operation_list_items: vec![
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentMedian },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentBilateral },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentGuided },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentNonLocalMeans },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentAnisotropicDiffusion },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentSnn },
                ]},
                OperationListItem::Category { name: "morphology".to_string(), operation_list_items: vec![
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentErode },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentDilate },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentOpen },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentClose },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentMorphGradient },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentTopHat },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentBlackHat },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentVectorMorphology },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentOutline },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentDistance },
                ]},
                OperationListItem::Category { name: "stylize".to_string(), operation_list_items: vec![
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentEmboss },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentKuwahara },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentAnisotropicKuwahara },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentToon },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentOilPaint },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentHalftone },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentCrossHatch },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentAscii },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentPixelate },
                ]},
                OperationListItem::Category { name: "dither".to_string(), operation_list_items: vec![
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentOrderedDither },
                    OperationListItem::Operation { operation: Operation::OpImageAdjustmentFloydSteinberg },
                ]},
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentConvolution },
            ]},
            OperationListItem::Category { name: "pbr".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImagePbrNormalFromHeight },
                OperationListItem::Operation { operation: Operation::OpImagePbrAoFromHeight },
                OperationListItem::Operation { operation: Operation::OpImagePbrCurvature },
                OperationListItem::Operation { operation: Operation::OpImagePbrHeightBlend },
                OperationListItem::Operation { operation: Operation::OpImagePbrNormalCombine },
                OperationListItem::Operation { operation: Operation::OpImagePbrNormalBlend },
                OperationListItem::Operation { operation: Operation::OpImagePbrNormalInvert },
                OperationListItem::Operation { operation: Operation::OpImagePbrNormalToHeight },
                OperationListItem::Operation { operation: Operation::OpImagePbrBevel },
            ]},
            OperationListItem::Category { name: "fx".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageFxDropShadow },
                OperationListItem::Operation { operation: Operation::OpImageFxOuterGlow },
                OperationListItem::Operation { operation: Operation::OpImageFxInnerGlow },
            ]},
            OperationListItem::Category { name: "channels".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageChannelSplit },
                OperationListItem::Operation { operation: Operation::OpImageChannelMerge },
                OperationListItem::Operation { operation: Operation::OpImageChannelShuffle },
                OperationListItem::Operation { operation: Operation::OpImageChannelSelect },
                OperationListItem::Operation { operation: Operation::OpImageChannelMixer },
            ]},
            OperationListItem::Category { name: "shapes".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageShapeRectangle },
                OperationListItem::Operation { operation: Operation::OpImageShapeEllipse },
                OperationListItem::Operation { operation: Operation::OpImageShapePolygon },
                OperationListItem::Operation { operation: Operation::OpImageShapeStar },
                OperationListItem::Operation { operation: Operation::OpImageShapeLine },
                OperationListItem::Operation { operation: Operation::OpImageShapeParaboloid },
                OperationListItem::Operation { operation: Operation::OpImageShapePyramid },
                OperationListItem::Operation { operation: Operation::OpImageShapeCone },
                OperationListItem::Operation { operation: Operation::OpImageShapesCircle },
            ]},
            OperationListItem::Category { name: "patterns".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImagePatternBrick },
                OperationListItem::Operation { operation: Operation::OpImagePatternHexagonal },
                OperationListItem::Operation { operation: Operation::OpImagePatternWeave },
                OperationListItem::Operation { operation: Operation::OpImagePatternTileSampler },
                OperationListItem::Operation { operation: Operation::OpImagePatternTileGenerator },
                OperationListItem::Operation { operation: Operation::OpImagePatternSplatter },
                OperationListItem::Operation { operation: Operation::OpImagePatternFloodFill },
                OperationListItem::Operation { operation: Operation::OpImagePatternFloodFillMapper },
            ]},
            OperationListItem::Category { name: "noise".to_string(), operation_list_items: vec![
                OperationListItem::Category { name: "basic".to_string(), operation_list_items: vec![
                    OperationListItem::Operation { operation: Operation::OpImageNoisePerlin },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseValue },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseOpenSimplex },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseSuperSimplex },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseGabor },
                    OperationListItem::Operation { operation: Operation::OpImageNoisePhasor },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseAnisotropic },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseGaussian },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseBlue },
                ]},
                OperationListItem::Category { name: "fractal".to_string(), operation_list_items: vec![
                    OperationListItem::Operation { operation: Operation::OpImageNoiseFbm },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseBillow },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseRidgedMultifractalNoise },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseHeterogenousMultifractalNoise },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseHybridMultifractalNoise },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseDomainWarpFbm },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseFlow },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseCurl },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseClouds },
                    OperationListItem::Operation { operation: Operation::OpImageNoisePlasma },
                ]},
                OperationListItem::Category { name: "cellular".to_string(), operation_list_items: vec![
                    OperationListItem::Operation { operation: Operation::OpImageNoiseWorleyDistance },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseWorleyValue },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseVoronoise },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseVoronoiCrack },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseCrystal },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseScales },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseCraters },
                ]},
                OperationListItem::Category { name: "structural".to_string(), operation_list_items: vec![
                    OperationListItem::Operation { operation: Operation::OpImageNoiseCheckerboard },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseCylinders },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseWave },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseTruchet },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseWarpedRings },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseVeins },
                ]},
                OperationListItem::Category { name: "grunge".to_string(), operation_list_items: vec![
                    OperationListItem::Operation { operation: Operation::OpImageNoiseDirt },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseScratches },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseFibers },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseLeaks },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseStains },
                    OperationListItem::Operation { operation: Operation::OpImageNoisePeeling },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseSmear },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseGrowth },
                ]},
                OperationListItem::Category { name: "process".to_string(), operation_list_items: vec![
                    OperationListItem::Operation { operation: Operation::OpImageNoiseErosion },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseFaultTerrain },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseReactionDiffusion },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseCaustics },
                    OperationListItem::Operation { operation: Operation::OpImageNoiseLightning },
                ]},
            ]},
            // Physical-process simulation generators (see plan.md for the backlog).
            OperationListItem::Category { name: "simulation".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageSimulationHydraulicErosion },
            ]},
            OperationListItem::Category { name: "cast".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageCastToImage },
            ]},
        ]},
        OperationListItem::Category { name: "logic".to_string(), operation_list_items: vec![
            OperationListItem::Category { name: "input".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpLogicInputBool },
            ]},
            OperationListItem::Category { name: "comparison".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpLogicCompareEqual },
                OperationListItem::Operation { operation: Operation::OpLogicCompareNotEqual },
                OperationListItem::Operation { operation: Operation::OpLogicCompareApproxEqual },
                OperationListItem::Operation { operation: Operation::OpLogicCompareInRange },
                OperationListItem::Operation { operation: Operation::OpLogicCompareLessThan },
                OperationListItem::Operation { operation: Operation::OpLogicCompareLessEqual },
                OperationListItem::Operation { operation: Operation::OpLogicCompareGreaterThan },
                OperationListItem::Operation { operation: Operation::OpLogicCompareGreaterEqual },
            ]},
            OperationListItem::Category { name: "boolean".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpLogicBoolAnd },
                OperationListItem::Operation { operation: Operation::OpLogicBoolOr },
                OperationListItem::Operation { operation: Operation::OpLogicBoolNot },
                OperationListItem::Operation { operation: Operation::OpLogicBoolXor },
                OperationListItem::Operation { operation: Operation::OpLogicBoolXnor },
                OperationListItem::Operation { operation: Operation::OpLogicBoolNand },
                OperationListItem::Operation { operation: Operation::OpLogicBoolNor },
            ]},
            OperationListItem::Category { name: "flow".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpLogicFlowSelect },
            ]},
            OperationListItem::Category { name: "text".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpLogicTextContains },
                OperationListItem::Operation { operation: Operation::OpLogicTextStartsWith },
                OperationListItem::Operation { operation: Operation::OpLogicTextEndsWith },
                OperationListItem::Operation { operation: Operation::OpLogicTextIsEmpty },
                OperationListItem::Operation { operation: Operation::OpLogicTextEqualsIgnoreCase },
            ]},
        ]},
        OperationListItem::Category { name: "text".to_string(), operation_list_items: vec![
            OperationListItem::Category { name: "input".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpTextInput },
            ]},
            OperationListItem::Category { name: "manipulation".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpTextAppend },
                OperationListItem::Operation { operation: Operation::OpTextLength },
                OperationListItem::Operation { operation: Operation::OpTextToUppercase },
                OperationListItem::Operation { operation: Operation::OpTextToLowercase },
                OperationListItem::Operation { operation: Operation::OpTextToString },
                OperationListItem::Operation { operation: Operation::OpTextJoin },
                OperationListItem::Operation { operation: Operation::OpTextReplace },
                OperationListItem::Operation { operation: Operation::OpTextSubstring },
                OperationListItem::Operation { operation: Operation::OpTextSplit },
                OperationListItem::Operation { operation: Operation::OpTextTrim },
                OperationListItem::Operation { operation: Operation::OpTextPad },
                OperationListItem::Operation { operation: Operation::OpTextRepeat },
                OperationListItem::Operation { operation: Operation::OpTextReverse },
                OperationListItem::Operation { operation: Operation::OpTextTemplate },
                OperationListItem::Operation { operation: Operation::OpTextTitleCase },
                OperationListItem::Operation { operation: Operation::OpTextFormatNumber },
            ]},
            OperationListItem::Category { name: "image".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpTextImageAsciiArt },
                OperationListItem::Operation { operation: Operation::OpTextImageDataUri },
                OperationListItem::Operation { operation: Operation::OpTextImageInfo },
                OperationListItem::Operation { operation: Operation::OpTextImagePaletteHex },
                OperationListItem::Operation { operation: Operation::OpTextImageHash },
            ]},
            OperationListItem::Category { name: "encoding".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpTextBase64Encode },
                OperationListItem::Operation { operation: Operation::OpTextBase64Decode },
                OperationListItem::Operation { operation: Operation::OpTextUrlEncode },
                OperationListItem::Operation { operation: Operation::OpTextUrlDecode },
            ]},
        ]},
    ];
    OperationListItem::sort_alphabetically(&mut list);
    // Subgraph is appended after sorting so it always appears at the bottom
    // of the node menu rather than slotting alphabetically between categories.
    list.push(OperationListItem::Subgraph);
    list
}





#[cfg(test)]
#[path = "operations_tests.rs"]
mod tests;
