//! Operation registry and shared types for the node graph engine.
//!
//! This module defines the [`Operation`] enum (generated by the [`operations!`] macro),
//! the hierarchical [`OperationListItem`] menu structure, and common types used by
//! all operation implementations such as [`ConnectionSettings`], [`OperationResponse`],
//! and [`OperationError`].

use crate::value::{Value, ValueType};
use crate::input::Input;
use crate::float_image::FloatImage;
use serde::{Deserialize, Serialize};
use core::fmt::Debug;
use std::sync::Arc;
use std::time::Duration;
use crate::node_settings::NodeSettings;
use crate::output::Output;

/// Numeric operations (inputs, arithmetic, interpolation, algebra, random, cast, logarithmic).
pub mod numbers;
/// Image operations (inputs, outputs, transforms, adjustments, blur, filter, noise, etc.).
pub mod images;
/// Color operations (inputs, outputs, blending, analysis).
pub mod colors;
/// Logic operations (boolean, comparison, flow control).
pub mod logic;
/// Text operations (clipboard).
pub mod text;
/// Video operations (file input, frame extraction).
pub mod videos;

/// Describes a single input or output connection slot on a node.
///
/// Used during node creation to define the name, default value, accepted types,
/// and UI presentation for each connection point.
#[derive(Debug, Clone)]
pub struct ConnectionSettings {
    /// Display name shown next to the connection in the UI.
    pub name: String,
    /// Initial value before any connection or user edit.
    pub default_value: Value,
    /// Set of value types this connection can accept or produce.
    pub valid_types: Vec<ValueType>,
    /// UI widget to use for editing; `None` for output connections (not directly editable).
    pub ui_type: Option<UiType>,
}

/// Widget type used by the GUI to render an input connection's editor.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum UiType {
    /// Numeric drag-to-edit widget.
    DragValue,
    /// Boolean toggle checkbox.
    Checkbox,
    /// Numeric slider with a range.
    Slider,
    /// Free-form text input field.
    TextEdit,
    /// Dropdown selection from a list of variants.
    ComboBox,
    /// Clickable button that emits a trigger.
    UiButton,
}

/// Successful result of executing a node operation.
// TODO: somehow find errors in inputs
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OperationResponse {
    /// One response per output slot, carrying the computed value.
    pub responses: Vec<OutputResponse>,
    /// Wall-clock time the operation took to execute.
    pub time: Duration,
}

/// A single output value produced by an operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutputResponse {
    /// The computed output value.
    pub value: Value,
}

/// Error returned when an operation fails to execute.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OperationError {
    /// Per-input errors: each entry is `(input_index, error_message)`.
    pub input_errors: Vec<(usize, String)>,
    /// An error on the node itself, independent of any particular input.
    pub node_error: Option<String>,
}

/// Converts an input value to the target type, pushing any error to `errors`.
/// Returns `Some(value)` on success, `None` on failure (error is recorded).
pub fn convert_input(
    inputs: &[Input],
    index: usize,
    target_type: ValueType,
    errors: &mut Vec<(usize, String)>,
) -> Option<Value> {
    match inputs[index].value.try_convert_to(target_type) {
        Ok(v) => Some(v),
        Err(e) => {
            errors.push((index, e.message));
            None
        }
    }
}

/// A node in the hierarchical operation menu tree.
///
/// The GUI uses this to build the "Add Node" context menu with nested categories.
#[derive(Clone)]
pub enum OperationListItem {
    /// A named folder that contains child items (subcategories or operations).
    Category {
        /// Display name for the category.
        name: String,
        /// Child items within this category.
        operation_list_items: Vec<OperationListItem>,
    },
    /// A leaf item representing a single operation that can be added to the graph.
    Operation {
        /// The operation variant to instantiate when selected.
        operation: Operation,
    },
    /// Placeholder for adding a subgraph node.
    Subgraph
}

impl OperationListItem {
    /// Returns the display name for sorting: category name or operation settings name.
    fn sort_name(&self) -> String {
        match self {
            OperationListItem::Category { name, .. } => name.clone(),
            OperationListItem::Operation { operation } => operation.settings().name,
            OperationListItem::Subgraph => "subgraph".to_string(),
        }
    }

    /// Recursively sorts all categories and operations alphabetically by name.
    pub fn sort_alphabetically(items: &mut Vec<OperationListItem>) {
        items.sort_by_key(|a| a.sort_name());
        for item in items.iter_mut() {
            if let OperationListItem::Category { operation_list_items, .. } = item {
                Self::sort_alphabetically(operation_list_items);
            }
        }
    }
}

/// Creates a 1x1 opaque white 4-channel FloatImage wrapped in an `Arc`.
///
/// Used as the default placeholder image for image-typed inputs.
pub fn default_image() -> Arc<FloatImage> {
    Arc::new(FloatImage::from_pixel(1, 1, 4, &[1.0, 1.0, 1.0, 1.0]))
}

/// Generates the [`Operation`] enum and its method dispatch implementations.
///
/// Each variant maps to an operation struct that provides `settings()`,
/// `create_inputs()`, `create_outputs()`, and `async fn run()`. The macro
/// generates match arms that delegate each `Operation` method call to the
/// corresponding struct's static/async methods.
#[macro_export]
macro_rules! operations {
    ( $($variant:ident($inner:ty)),* $(,)?) => {
        #[derive(Debug, Serialize, Deserialize, Clone)]
        pub enum Operation {
            $($variant,)*
        }

        impl Operation {
            pub fn settings(&self) -> NodeSettings {
                match self {
                    $(Operation::$variant => <$inner>::settings(),)*
                }
            }

            pub fn create_inputs(&self) -> Vec<Input> {
                match self {
                    $(Operation::$variant => <$inner>::create_inputs(),)*
                }
            }

            pub fn create_outputs(&self) -> Vec<Output> {
                match self {
                    $(Operation::$variant => <$inner>::create_outputs(),)*
                }
            }

            pub async fn run(&self, inputs: &mut [Input]) -> Result<$crate::operations::OperationResponse, $crate::operations::OperationError> {
                match self {
                    $(Operation::$variant => <$inner>::run(inputs).await,)*
                }
            }
        }
    };
}

operations! {
    // numbers
    OpNumberInputInteger(crate::operations::numbers::inputs::integer::OpNumberInputInteger),
    OpNumberInputDecimal(crate::operations::numbers::inputs::decimal::OpNumberInputDecimal),
    OpNumberInputPi(crate::operations::numbers::inputs::pi::OpNumberInputPi),
    OpNumberInputTau(crate::operations::numbers::inputs::tau::OpNumberInputTau),
    OpNumberInputE(crate::operations::numbers::inputs::e::OpNumberInputE),

    OpNumberMathAdd(crate::operations::numbers::arithmetic::add::OpNumberMathAdd),
    OpNumberMathSubtract(crate::operations::numbers::arithmetic::subtract::OpNumberMathSubtract),
    OpNumberMathMultiply(crate::operations::numbers::arithmetic::multiply::OpNumberMathMultiply),
    OpNumberMathDivide(crate::operations::numbers::arithmetic::divide::OpNumberMathDivide),
    OpNumberMathDecrement(crate::operations::numbers::arithmetic::decrement::OpNumberMathDecrement),
    OpNumberMathIncrement(crate::operations::numbers::arithmetic::increment::OpNumberMathIncrement),
    OpNumberMathMax(crate::operations::numbers::arithmetic::max::OpNumberMathMax),
    OpNumberMathMin(crate::operations::numbers::arithmetic::min::OpNumberMathMin),
    OpNumberMathClamp(crate::operations::numbers::arithmetic::clamp::OpNumberMathClamp),
    OpNumberMathModulus(crate::operations::numbers::arithmetic::modulus::OpNumberMathModulus),
    OpNumberMathRound(crate::operations::numbers::arithmetic::round::OpNumberMathRound),
    OpNumberMathSign(crate::operations::numbers::arithmetic::sign::OpNumberMathSign),
    OpNumberMathNegate(crate::operations::numbers::arithmetic::negate::OpNumberMathNegate),
    OpNumberMathReciprocal(crate::operations::numbers::arithmetic::reciprocal::OpNumberMathReciprocal),
    OpNumberMathAverage(crate::operations::numbers::arithmetic::average::OpNumberMathAverage),
    OpNumberMathCeil(crate::operations::numbers::arithmetic::ceil::OpNumberMathCeil),
    OpNumberMathFloor(crate::operations::numbers::arithmetic::floor::OpNumberMathFloor),
    OpNumberMathTrunc(crate::operations::numbers::arithmetic::trunc::OpNumberMathTrunc),
    OpNumberMathFrac(crate::operations::numbers::arithmetic::frac::OpNumberMathFrac),

    // interpolation
    OpNumberMathStep(crate::operations::numbers::interpolation::step::OpNumberMathStep),
    OpNumberMathSmoothstep(crate::operations::numbers::interpolation::smoothstep::OpNumberMathSmoothstep),
    OpNumberMathLerp(crate::operations::numbers::interpolation::lerp::OpNumberMathLerp),
    OpNumberMathMapRange(crate::operations::numbers::interpolation::map_range::OpNumberMathMapRange),

    // trigonometry
    OpNumberTrigSin(crate::operations::numbers::trigonometry::sin::OpNumberTrigSin),
    OpNumberTrigCos(crate::operations::numbers::trigonometry::cos::OpNumberTrigCos),
    OpNumberTrigTan(crate::operations::numbers::trigonometry::tan::OpNumberTrigTan),
    OpNumberTrigAsin(crate::operations::numbers::trigonometry::asin::OpNumberTrigAsin),
    OpNumberTrigAcos(crate::operations::numbers::trigonometry::acos::OpNumberTrigAcos),
    OpNumberTrigAtan(crate::operations::numbers::trigonometry::atan::OpNumberTrigAtan),
    OpNumberTrigAtan2(crate::operations::numbers::trigonometry::atan2::OpNumberTrigAtan2),
    OpNumberTrigSinh(crate::operations::numbers::trigonometry::sinh::OpNumberTrigSinh),
    OpNumberTrigCosh(crate::operations::numbers::trigonometry::cosh::OpNumberTrigCosh),
    OpNumberTrigTanh(crate::operations::numbers::trigonometry::tanh::OpNumberTrigTanh),

    // random
    OpNumberRandomDecimal(crate::operations::numbers::random::random_decimal::OpNumberRandomDecimal),
    OpNumberRandomInteger(crate::operations::numbers::random::random_integer::OpNumberRandomInteger),

    // algebra
    OpNumberMathAbs(crate::operations::numbers::algebra::abs::OpNumberMathAbs),
    OpNumberMathSqrt(crate::operations::numbers::algebra::sqrt::OpNumberMathSqrt),
    OpNumberMathCbrt(crate::operations::numbers::algebra::cbrt::OpNumberMathCbrt),
    OpNumberMathNthRt(crate::operations::numbers::algebra::nth_root::OpNumberMathNthRt),
    OpNumberMathPow(crate::operations::numbers::algebra::pow::OpNumberMathPow),
    OpNumberMathFactorial(crate::operations::numbers::algebra::factorial::OpNumberMathFactorial),
    OpNumberMathGcd(crate::operations::numbers::algebra::gcd::OpNumberMathGcd),
    OpNumberMathLcm(crate::operations::numbers::algebra::lcm::OpNumberMathLcm),

    // cast
    OpNumberCastToDecimal(crate::operations::numbers::cast::to_decimal::OpNumberCastToDecimal),
    OpNumberCastToInteger(crate::operations::numbers::cast::to_integer::OpNumberCastToInteger),

    // logarithmic
    OpNumberMathLog(crate::operations::numbers::logarithmic::log::OpNumberMathLog),
    OpNumberMathLn(crate::operations::numbers::logarithmic::ln::OpNumberMathLn),
    OpNumberMathExp(crate::operations::numbers::logarithmic::exp::OpNumberMathExp),
    OpNumberMathLog2(crate::operations::numbers::logarithmic::log2::OpNumberMathLog2),
    OpNumberMathLog10(crate::operations::numbers::logarithmic::log10::OpNumberMathLog10),

    // colors
    OpColorInputCmyk(crate::operations::colors::inputs::cmyk::OpColorInputCmyk),
    OpColorInputHsl(crate::operations::colors::inputs::hsl::OpColorInputHsla),
    OpColorInputHsv(crate::operations::colors::inputs::hsv::OpColorInputHsva),
    OpColorInputLab(crate::operations::colors::inputs::lab::OpColorInputLab),
    OpColorInputLch(crate::operations::colors::inputs::lch::OpColorInputLch),
    OpColorInputRgbLinear(crate::operations::colors::inputs::rgb_linear::OpColorInputRgbaLinear),
    OpColorInputRgb(crate::operations::colors::inputs::srgb::OpColorInputRgba),
    OpColorInputXyz(crate::operations::colors::inputs::xyz::OpColorInputXyz),
    OpColorInputYuv(crate::operations::colors::inputs::yuv::OpColorInputYuv),

    OpColorOutputCmyk(crate::operations::colors::outputs::to_cmyk::OpColorOutputCmyk),
    OpColorOutputHsl(crate::operations::colors::outputs::to_hsl::OpColorOutputHsl),
    OpColorOutputHsv(crate::operations::colors::outputs::to_hsv::OpColorOutputHsv),
    OpColorOutputLab(crate::operations::colors::outputs::to_lab::OpColorOutputLab),
    OpColorOutputLch(crate::operations::colors::outputs::to_lch::OpColorOutputLch),
    OpColorOutputRgbLinear(crate::operations::colors::outputs::to_rgb_linear::OpColorOutputRgbLinear),
    OpColorOutputRgb(crate::operations::colors::outputs::to_srgb::OpColorOutputRgb),
    OpColorOutputXyz(crate::operations::colors::outputs::to_xyz::OpColorOutputXyz),
    OpColorOutputYuv(crate::operations::colors::outputs::to_yuv::OpColorOutputYuv),

    OpColorBlendMode(crate::operations::colors::blend::blend_mode::OpColorBlendMode),

    OpColorSampleMostCommonColors(crate::operations::colors::sample_image::most_common_colors::OpColorSampleMostCommonColors),

    OpColorCastToColor(crate::operations::colors::cast::to_color::OpColorCastToColor),

    OpColorGenerationFromHex(crate::operations::colors::generation::from_hex::OpColorGenerationFromHex),
    OpColorGenerationToHex(crate::operations::colors::generation::to_hex::OpColorGenerationToHex),
    OpColorGenerationRandomColor(crate::operations::colors::generation::random_color::OpColorGenerationRandomColor),

    OpColorManipulationInvert(crate::operations::colors::manipulation::invert::OpColorManipulationInvert),
    OpColorManipulationGrayscale(crate::operations::colors::manipulation::grayscale::OpColorManipulationGrayscale),
    OpColorManipulationAdjustHsv(crate::operations::colors::manipulation::adjust_hsv::OpColorManipulationAdjustHsv),
    OpColorManipulationClamp(crate::operations::colors::manipulation::clamp::OpColorManipulationClamp),
    OpColorManipulationSetAlpha(crate::operations::colors::manipulation::set_alpha::OpColorManipulationSetAlpha),

    OpColorAnalysisDistance(crate::operations::colors::analysis::distance::OpColorAnalysisDistance),
    OpColorAnalysisLuminance(crate::operations::colors::analysis::luminance::OpColorAnalysisLuminance),
    OpColorAnalysisContrastRatio(crate::operations::colors::analysis::contrast_ratio::OpColorAnalysisContrastRatio),
    OpColorAnalysisColorTemperature(crate::operations::colors::analysis::color_temperature::OpColorAnalysisColorTemperature),
    OpColorAnalysisDominantHue(crate::operations::colors::analysis::dominant_hue::OpColorAnalysisDominantHue),
    OpColorAnalysisHarmonyScore(crate::operations::colors::analysis::harmony_score::OpColorAnalysisHarmonyScore),
    OpColorAnalysisMixRatio(crate::operations::colors::analysis::mix_ratio::OpColorAnalysisMixRatio),

    OpColorHarmonyComplementary(crate::operations::colors::relationship::complementary::OpColorHarmonyComplementary),
    OpColorHarmonyTriadic(crate::operations::colors::relationship::triadic::OpColorHarmonyTriadic),
    OpColorHarmonyAnalogous(crate::operations::colors::relationship::analogous::OpColorHarmonyAnalogous),
    OpColorHarmonyTetradic(crate::operations::colors::relationship::tetradic::OpColorHarmonyTetradic),
    OpColorHarmonyDoubleSplitComplementary(crate::operations::colors::relationship::double_split_complementary::OpColorHarmonyDoubleSplitComplementary),
    OpColorHarmonyMonochromatic(crate::operations::colors::relationship::monochromatic::OpColorHarmonyMonochromatic),

    // image
    OpImageInputUrl(crate::operations::images::inputs::url::OpImageInputUrl),
    OpImageInputClipboard(crate::operations::images::inputs::clipboard::OpImageInputClipboard),
    OpImageInputColor(crate::operations::images::inputs::color::OpImageInputColor),
    OpImageInputFile(crate::operations::images::inputs::file::OpImageInputFile),
    OpImageInputGradient(crate::operations::images::inputs::gradient::OpImageInputGradient),
    OpImageInputText(crate::operations::images::inputs::text::OpImageInputText),

    OpImageOutputClipboard(crate::operations::images::outputs::clipboard::OpImageOutputClipboard),
    OpImageOutputFile(crate::operations::images::outputs::file::OpImageOutputFile),

    OpImageCombineBlit(crate::operations::images::combine::blit::OpImageCombineBlit),
    OpImageCombineBlend(crate::operations::images::combine::blend::OpImageCombineBlend),
    OpImageCombineCompare(crate::operations::images::combine::compare::OpImageCombineCompare),

    OpImageTransformCrop(crate::operations::images::transform::crop::OpImageTransformCrop),
    OpImageTransformResize(crate::operations::images::transform::resize::OpImageTransformResize),
    OpImageTransformResizeExact(crate::operations::images::transform::resize_exact::OpImageTransformResizeExact),
    OpImageTransformResizeFill(crate::operations::images::transform::resize_fill::OpImageTransformResizeFill),
    OpImageTransformFlipHorizontal(crate::operations::images::transform::flip_horizontal::OpImageTransformFlipHorizontal),
    OpImageTransformFlipVertical(crate::operations::images::transform::flip_vertical::OpImageTransformFlipVertical),
    OpImageTransformRotate90(crate::operations::images::transform::rotate_90::OpImageTransformRotate90),
    OpImageTransformRotate180(crate::operations::images::transform::rotate_180::OpImageTransformRotate180),
    OpImageTransformRotate270(crate::operations::images::transform::rotate_270::OpImageTransformRotate270),
    OpImageTransformRotateAroundCenter(crate::operations::images::transform::rotate_around_center::OpImageTransformRotateAroundCenter),

    OpImageTransformWarp(crate::operations::images::transform::warp::OpImageTransformWarp),
    OpImageTransformDirectionalWarp(crate::operations::images::transform::directional_warp::OpImageTransformDirectionalWarp),
    OpImageTransformSafeTransform(crate::operations::images::transform::safe_transform::OpImageTransformSafeTransform),
    OpImageTransformMakeTile(crate::operations::images::transform::make_tile::OpImageTransformMakeTile),
    OpImageTransformMirror(crate::operations::images::transform::mirror::OpImageTransformMirror),
    OpImageTransformSeamCarve(crate::operations::images::transform::seam_carve::OpImageTransformSeamCarve),

    // blur
    OpImageAdjustmentBlur(crate::operations::images::blur::blur::OpImageAdjustmentBlur),
    OpImageAdjustmentContrast(crate::operations::images::adjustments::contrast::OpImageAdjustmentContrast),
    OpImageAdjustmentGrayscale(crate::operations::images::adjustments::grayscale::OpImageAdjustmentGrayscale),
    OpImageAdjustmentInvert(crate::operations::images::adjustments::invert::OpImageAdjustmentInvert),
    OpImageAdjustmentBrighten(crate::operations::images::adjustments::brighten::OpImageAdjustmentBrighten),
    OpImageAdjustmentHueRotate(crate::operations::images::adjustments::hue_rotate::OpImageAdjustmentHueRotate),
    OpImageAdjustmentUnsharpen(crate::operations::images::filter::unsharpen::OpImageAdjustmentUnsharpen),
    OpImageAdjustmentLevels(crate::operations::images::adjustments::levels::OpImageAdjustmentLevels),
    OpImageAdjustmentCurves(crate::operations::images::adjustments::curves::OpImageAdjustmentCurves),
    OpImageAdjustmentGradientMap(crate::operations::images::adjustments::gradient_map::OpImageAdjustmentGradientMap),

    OpImageAdjustmentDirectionalBlur(crate::operations::images::blur::directional_blur::OpImageAdjustmentDirectionalBlur),
    OpImageAdjustmentRadialBlur(crate::operations::images::blur::radial_blur::OpImageAdjustmentRadialBlur),
    OpImageAdjustmentSlopeBlur(crate::operations::images::blur::slope_blur::OpImageAdjustmentSlopeBlur),
    OpImageAdjustmentNonUniformBlur(crate::operations::images::blur::non_uniform_blur::OpImageAdjustmentNonUniformBlur),

    // filter
    OpImageAdjustmentEdgeDetect(crate::operations::images::filter::edge_detect::OpImageAdjustmentEdgeDetect),
    OpImageAdjustmentEmboss(crate::operations::images::filter::emboss::OpImageAdjustmentEmboss),
    OpImageAdjustmentSharpen(crate::operations::images::filter::sharpen::OpImageAdjustmentSharpen),
    OpImageAdjustmentKuwahara(crate::operations::images::filter::kuwahara::OpImageAdjustmentKuwahara),
    OpImageAdjustmentAnisotropicKuwahara(crate::operations::images::filter::anisotropic_kuwahara::OpImageAdjustmentAnisotropicKuwahara),
    OpImageAdjustmentBilateral(crate::operations::images::filter::bilateral::OpImageAdjustmentBilateral),
    OpImageAdjustmentSnn(crate::operations::images::filter::snn::OpImageAdjustmentSnn),
    OpImageAdjustmentToon(crate::operations::images::filter::toon::OpImageAdjustmentToon),
    OpImageAdjustmentMedian(crate::operations::images::filter::median::OpImageAdjustmentMedian),
    OpImageAdjustmentGuided(crate::operations::images::filter::guided::OpImageAdjustmentGuided),
    OpImageAdjustmentPosterize(crate::operations::images::adjustments::posterize::OpImageAdjustmentPosterize),
    OpImageAdjustmentHistogramScan(crate::operations::images::adjustments::histogram_scan::OpImageAdjustmentHistogramScan),
    OpImageAdjustmentHistogramRange(crate::operations::images::adjustments::histogram_range::OpImageAdjustmentHistogramRange),
    OpImageAdjustmentAutoLevels(crate::operations::images::adjustments::auto_levels::OpImageAdjustmentAutoLevels),
    OpImageAdjustmentDistance(crate::operations::images::adjustments::distance::OpImageAdjustmentDistance),

    OpImageChannelSplit(crate::operations::images::channels::split::OpImageChannelSplit),
    OpImageChannelMerge(crate::operations::images::channels::merge::OpImageChannelMerge),
    OpImageChannelShuffle(crate::operations::images::channels::shuffle::OpImageChannelShuffle),

    OpImageNoisePerlin(crate::operations::images::noise::perlin::OpImageNoisePerlin),
    OpImageNoiseWorleyDistance(crate::operations::images::noise::worley_distance::OpImageNoiseWorleyDistance),
    OpImageNoiseWorleyValue(crate::operations::images::noise::worley_value::OpImageNoiseWorleyValue),
    OpImageNoiseHeterogenousMultifractalNoise(crate::operations::images::noise::basic_multifractal::OpImageNoiseHeterogenousMultifractalNoise),
    OpImageNoiseBillow(crate::operations::images::noise::billow::OpImageNoiseBillow),
    OpImageNoiseCylinders(crate::operations::images::noise::cylinders::OpImageNoiseCylinders),
    OpImageNoiseDomainWarpFbm(crate::operations::images::noise::domain_warp_fbm::OpImageNoiseDomainWarpFbm),
    OpImageNoiseFbm(crate::operations::images::noise::fbm::OpImageNoiseFbm),
    OpImageNoiseHybridMultifractalNoise(crate::operations::images::noise::hybrid_multifractal::OpImageNoiseHybridMultifractalNoise),
    OpImageNoiseOpenSimplex(crate::operations::images::noise::open_simplex::OpImageNoiseOpenSimplex),
    OpImageNoiseSuperSimplex(crate::operations::images::noise::super_simplex::OpImageNoiseSuperSimplex),
    OpImageNoiseRidgedMultifractalNoise(crate::operations::images::noise::ridged_multifractal::OpImageNoiseRidgedMultifractalNoise),
    OpImageNoiseValue(crate::operations::images::noise::value::OpImageNoiseValue),
    OpImageNoiseVoronoiCrack(crate::operations::images::noise::voronoi_crack::OpImageNoiseVoronoiCrack),
    OpImageNoiseVoronoise(crate::operations::images::noise::voronoise::OpImageNoiseVoronoise),
    OpImageNoiseReactionDiffusion(crate::operations::images::noise::reaction_diffusion::OpImageNoiseReactionDiffusion),
    OpImageNoiseErosion(crate::operations::images::noise::erosion::OpImageNoiseErosion),
    OpImageNoiseGabor(crate::operations::images::noise::gabor::OpImageNoiseGabor),
    OpImageNoiseGaussian(crate::operations::images::noise::gaussian::OpImageNoiseGaussian),
    OpImageNoiseCrystal(crate::operations::images::noise::crystal::OpImageNoiseCrystal),
    OpImageNoiseClouds(crate::operations::images::noise::clouds::OpImageNoiseClouds),
    OpImageNoisePlasma(crate::operations::images::noise::plasma::OpImageNoisePlasma),
    OpImageNoiseAnisotropic(crate::operations::images::noise::anisotropic::OpImageNoiseAnisotropic),
    OpImageNoiseDirt(crate::operations::images::noise::dirt::OpImageNoiseDirt),

    // shapes
    OpImageShapeRectangle(crate::operations::images::shapes::rectangle::OpImageShapeRectangle),
    OpImageShapeEllipse(crate::operations::images::shapes::ellipse::OpImageShapeEllipse),
    OpImageShapePolygon(crate::operations::images::shapes::polygon::OpImageShapePolygon),
    OpImageShapeStar(crate::operations::images::shapes::star::OpImageShapeStar),
    OpImageShapeLine(crate::operations::images::shapes::line::OpImageShapeLine),

    // patterns
    OpImagePatternBrick(crate::operations::images::patterns::brick::OpImagePatternBrick),
    OpImagePatternHexagonal(crate::operations::images::patterns::hexagonal::OpImagePatternHexagonal),
    OpImagePatternWeave(crate::operations::images::patterns::weave::OpImagePatternWeave),
    OpImagePatternTileSampler(crate::operations::images::patterns::tile_sampler::OpImagePatternTileSampler),

    // pbr
    OpImagePbrNormalFromHeight(crate::operations::images::pbr::normal_from_height::OpImagePbrNormalFromHeight),
    OpImagePbrAoFromHeight(crate::operations::images::pbr::ao_from_height::OpImagePbrAoFromHeight),
    OpImagePbrCurvature(crate::operations::images::pbr::curvature::OpImagePbrCurvature),
    OpImagePbrHeightBlend(crate::operations::images::pbr::height_blend::OpImagePbrHeightBlend),

    OpImageCastToImage(crate::operations::images::cast::to_image::OpImageCastToImage),

    // logic
    OpLogicInputBool(crate::operations::logic::inputs::bool_input::OpLogicInputBool),

    OpLogicCompareEqual(crate::operations::logic::comparison::equal::OpLogicCompareEqual),
    OpLogicCompareNotEqual(crate::operations::logic::comparison::not_equal::OpLogicCompareNotEqual),
    OpLogicCompareLessThan(crate::operations::logic::comparison::less_than::OpLogicCompareLessThan),
    OpLogicCompareLessEqual(crate::operations::logic::comparison::less_equal::OpLogicCompareLessEqual),
    OpLogicCompareGreaterThan(crate::operations::logic::comparison::greater_than::OpLogicCompareGreaterThan),
    OpLogicCompareGreaterEqual(crate::operations::logic::comparison::greater_equal::OpLogicCompareGreaterEqual),

    OpLogicBoolAnd(crate::operations::logic::boolean::and::OpLogicBoolAnd),
    OpLogicBoolOr(crate::operations::logic::boolean::or::OpLogicBoolOr),
    OpLogicBoolNot(crate::operations::logic::boolean::not::OpLogicBoolNot),
    OpLogicBoolXor(crate::operations::logic::boolean::xor::OpLogicBoolXor),
    OpLogicBoolNand(crate::operations::logic::boolean::nand::OpLogicBoolNand),
    OpLogicBoolNor(crate::operations::logic::boolean::nor::OpLogicBoolNor),

    OpLogicFlowSelect(crate::operations::logic::flow::select::OpLogicFlowSelect),

    // text
    OpTextInput(crate::operations::text::inputs::text_input::OpTextInput),
    OpTextAppend(crate::operations::text::manipulation::append::OpTextAppend),
    OpTextLength(crate::operations::text::manipulation::length::OpTextLength),
    OpTextToUppercase(crate::operations::text::manipulation::to_uppercase::OpTextToUppercase),
    OpTextToLowercase(crate::operations::text::manipulation::to_lowercase::OpTextToLowercase),
    OpTextToString(crate::operations::text::manipulation::to_string::OpTextToString),

    // bitwise
    OpNumberBitwiseAnd(crate::operations::numbers::bitwise::bit_and::OpNumberBitwiseAnd),
    OpNumberBitwiseOr(crate::operations::numbers::bitwise::bit_or::OpNumberBitwiseOr),
    OpNumberBitwiseXor(crate::operations::numbers::bitwise::bit_xor::OpNumberBitwiseXor),
    OpNumberBitwiseNot(crate::operations::numbers::bitwise::bit_not::OpNumberBitwiseNot),
    OpNumberBitwiseShiftLeft(crate::operations::numbers::bitwise::bit_shift_left::OpNumberBitwiseShiftLeft),
    OpNumberBitwiseShiftRight(crate::operations::numbers::bitwise::bit_shift_right::OpNumberBitwiseShiftRight),

    // videos
    OpVideoInputFile(crate::operations::videos::inputs::file::OpVideoInputFile),
    OpVideoOutputFile(crate::operations::videos::outputs::file::OpVideoOutputFile),
}

impl Operation {
    /// Returns true if this operation's output depends on a render-clock time
    /// value that the engine should drive during a video render. Used by the
    /// render task to identify which nodes to override each frame.
    pub fn is_time_aware(&self) -> bool {
        matches!(self, Operation::OpVideoInputFile)
    }

    /// Engine hook invoked once per render frame before `graph.run()`. Updates
    /// time-driven inputs on the node so the next run produces the frame for
    /// `render_time_seconds`. No-op for operations where `is_time_aware()` is
    /// false.
    pub fn apply_render_time(&self, inputs: &mut [crate::input::Input], render_time_seconds: f64) {
        match self {
            Operation::OpVideoInputFile => {
                crate::operations::videos::inputs::file::OpVideoInputFile::apply_render_time(
                    inputs,
                    render_time_seconds,
                );
            }
            _ => {}
        }
    }
}

/// Returns the full hierarchical menu of available operations.
///
/// This defines the structure of the "Add Node" context menu in the GUI,
/// organized into top-level categories (numbers, colors, images, logic)
/// with nested subcategories.
pub fn operation_list() -> Vec<OperationListItem> {
    let mut list = vec![
        OperationListItem::Category { name: "numbers".to_string(), operation_list_items: vec![
            OperationListItem::Category { name: "input".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberInputDecimal },
                OperationListItem::Operation { operation: Operation::OpNumberInputInteger },
                OperationListItem::Operation { operation: Operation::OpNumberInputPi },
                OperationListItem::Operation { operation: Operation::OpNumberInputTau },
                OperationListItem::Operation { operation: Operation::OpNumberInputE },
            ]},
            OperationListItem::Category { name: "arithmetic".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberMathAdd },
                OperationListItem::Operation { operation: Operation::OpNumberMathSubtract },
                OperationListItem::Operation { operation: Operation::OpNumberMathMultiply },
                OperationListItem::Operation { operation: Operation::OpNumberMathDivide },
                OperationListItem::Operation { operation: Operation::OpNumberMathIncrement },
                OperationListItem::Operation { operation: Operation::OpNumberMathDecrement },
                OperationListItem::Operation { operation: Operation::OpNumberMathMax },
                OperationListItem::Operation { operation: Operation::OpNumberMathMin },
                OperationListItem::Operation { operation: Operation::OpNumberMathClamp },
                OperationListItem::Operation { operation: Operation::OpNumberMathModulus },
                OperationListItem::Operation { operation: Operation::OpNumberMathRound },
                OperationListItem::Operation { operation: Operation::OpNumberMathSign },
                OperationListItem::Operation { operation: Operation::OpNumberMathNegate },
                OperationListItem::Operation { operation: Operation::OpNumberMathReciprocal },
                OperationListItem::Operation { operation: Operation::OpNumberMathAverage },
                OperationListItem::Operation { operation: Operation::OpNumberMathCeil },
                OperationListItem::Operation { operation: Operation::OpNumberMathFloor },
                OperationListItem::Operation { operation: Operation::OpNumberMathTrunc },
                OperationListItem::Operation { operation: Operation::OpNumberMathFrac },
            ]},
            OperationListItem::Category { name: "interpolation".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberMathLerp },
                OperationListItem::Operation { operation: Operation::OpNumberMathSmoothstep },
                OperationListItem::Operation { operation: Operation::OpNumberMathStep },
                OperationListItem::Operation { operation: Operation::OpNumberMathMapRange },
            ]},
            OperationListItem::Category { name: "trigonometry".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberTrigSin },
                OperationListItem::Operation { operation: Operation::OpNumberTrigCos },
                OperationListItem::Operation { operation: Operation::OpNumberTrigTan },
                OperationListItem::Operation { operation: Operation::OpNumberTrigAsin },
                OperationListItem::Operation { operation: Operation::OpNumberTrigAcos },
                OperationListItem::Operation { operation: Operation::OpNumberTrigAtan },
                OperationListItem::Operation { operation: Operation::OpNumberTrigAtan2 },
                OperationListItem::Operation { operation: Operation::OpNumberTrigSinh },
                OperationListItem::Operation { operation: Operation::OpNumberTrigCosh },
                OperationListItem::Operation { operation: Operation::OpNumberTrigTanh },
            ]},
            OperationListItem::Category { name: "algebraic".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberMathAbs },
                OperationListItem::Operation { operation: Operation::OpNumberMathSqrt },
                OperationListItem::Operation { operation: Operation::OpNumberMathCbrt },
                OperationListItem::Operation { operation: Operation::OpNumberMathNthRt },
                OperationListItem::Operation { operation: Operation::OpNumberMathPow },
                OperationListItem::Operation { operation: Operation::OpNumberMathFactorial },
                OperationListItem::Operation { operation: Operation::OpNumberMathGcd },
                OperationListItem::Operation { operation: Operation::OpNumberMathLcm },
            ]},
            OperationListItem::Category { name: "cast".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberCastToDecimal },
                OperationListItem::Operation { operation: Operation::OpNumberCastToInteger },
            ]},
            OperationListItem::Category { name: "logarithmic".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberMathLog },
                OperationListItem::Operation { operation: Operation::OpNumberMathLn },
                OperationListItem::Operation { operation: Operation::OpNumberMathExp },
                OperationListItem::Operation { operation: Operation::OpNumberMathLog2 },
                OperationListItem::Operation { operation: Operation::OpNumberMathLog10 },
            ]},
            OperationListItem::Category { name: "random".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberRandomDecimal },
                OperationListItem::Operation { operation: Operation::OpNumberRandomInteger },
            ]},
            OperationListItem::Category { name: "bitwise".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpNumberBitwiseAnd },
                OperationListItem::Operation { operation: Operation::OpNumberBitwiseOr },
                OperationListItem::Operation { operation: Operation::OpNumberBitwiseXor },
                OperationListItem::Operation { operation: Operation::OpNumberBitwiseNot },
                OperationListItem::Operation { operation: Operation::OpNumberBitwiseShiftLeft },
                OperationListItem::Operation { operation: Operation::OpNumberBitwiseShiftRight },
            ]},
        ]},
        OperationListItem::Category { name: "colors".to_string(), operation_list_items: vec![
            OperationListItem::Category { name: "input".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpColorInputCmyk },
                OperationListItem::Operation { operation: Operation::OpColorInputHsl },
                OperationListItem::Operation { operation: Operation::OpColorInputHsv },
                OperationListItem::Operation { operation: Operation::OpColorInputLab },
                OperationListItem::Operation { operation: Operation::OpColorInputLch },
                OperationListItem::Operation { operation: Operation::OpColorInputRgb },
                OperationListItem::Operation { operation: Operation::OpColorInputRgbLinear },
                OperationListItem::Operation { operation: Operation::OpColorInputXyz },
                OperationListItem::Operation { operation: Operation::OpColorInputYuv },
            ]},
            OperationListItem::Category { name: "output".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpColorOutputCmyk },
                OperationListItem::Operation { operation: Operation::OpColorOutputHsl },
                OperationListItem::Operation { operation: Operation::OpColorOutputHsv },
                OperationListItem::Operation { operation: Operation::OpColorOutputLab },
                OperationListItem::Operation { operation: Operation::OpColorOutputLch },
                OperationListItem::Operation { operation: Operation::OpColorOutputRgb },
                OperationListItem::Operation { operation: Operation::OpColorOutputRgbLinear },
                OperationListItem::Operation { operation: Operation::OpColorOutputXyz },
                OperationListItem::Operation { operation: Operation::OpColorOutputYuv },
            ]},
            OperationListItem::Category { name: "analysis".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpColorSampleMostCommonColors },
                OperationListItem::Operation { operation: Operation::OpColorAnalysisDistance },
                OperationListItem::Operation { operation: Operation::OpColorAnalysisLuminance },
                OperationListItem::Operation { operation: Operation::OpColorAnalysisContrastRatio },
                OperationListItem::Operation { operation: Operation::OpColorAnalysisColorTemperature },
                OperationListItem::Operation { operation: Operation::OpColorAnalysisDominantHue },
                OperationListItem::Operation { operation: Operation::OpColorAnalysisHarmonyScore },
                OperationListItem::Operation { operation: Operation::OpColorAnalysisMixRatio },
            ]},
            OperationListItem::Category { name: "generation".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpColorGenerationFromHex },
                OperationListItem::Operation { operation: Operation::OpColorGenerationToHex },
                OperationListItem::Operation { operation: Operation::OpColorGenerationRandomColor },
                OperationListItem::Operation { operation: Operation::OpColorCastToColor },
            ]},
            OperationListItem::Category { name: "manipulation".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpColorManipulationInvert },
                OperationListItem::Operation { operation: Operation::OpColorManipulationGrayscale },
                OperationListItem::Operation { operation: Operation::OpColorManipulationAdjustHsv },
                OperationListItem::Operation { operation: Operation::OpColorManipulationClamp },
                OperationListItem::Operation { operation: Operation::OpColorManipulationSetAlpha },
                OperationListItem::Operation { operation: Operation::OpColorBlendMode },
            ]},
            OperationListItem::Category { name: "harmony".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpColorHarmonyComplementary },
                OperationListItem::Operation { operation: Operation::OpColorHarmonyTriadic },
                OperationListItem::Operation { operation: Operation::OpColorHarmonyAnalogous },
                OperationListItem::Operation { operation: Operation::OpColorHarmonyTetradic },
                OperationListItem::Operation { operation: Operation::OpColorHarmonyDoubleSplitComplementary },
                OperationListItem::Operation { operation: Operation::OpColorHarmonyMonochromatic },
            ]},
        ]},
        OperationListItem::Category { name: "images".to_string(), operation_list_items: vec![
            OperationListItem::Category { name: "input".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageInputFile },
                OperationListItem::Operation { operation: Operation::OpImageInputUrl },
                OperationListItem::Operation { operation: Operation::OpImageInputClipboard },
                OperationListItem::Operation { operation: Operation::OpImageInputColor },
                OperationListItem::Operation { operation: Operation::OpImageInputGradient },
                OperationListItem::Operation { operation: Operation::OpImageInputText },
            ]},
            OperationListItem::Category { name: "output".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageOutputFile },
                OperationListItem::Operation { operation: Operation::OpImageOutputClipboard },
            ]},
            OperationListItem::Category { name: "combine".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageCombineBlit },
                OperationListItem::Operation { operation: Operation::OpImageCombineBlend },
                OperationListItem::Operation { operation: Operation::OpImageCombineCompare },
            ]},
            OperationListItem::Category { name: "transform".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageTransformCrop },
                OperationListItem::Operation { operation: Operation::OpImageTransformResize },
                OperationListItem::Operation { operation: Operation::OpImageTransformResizeExact },
                OperationListItem::Operation { operation: Operation::OpImageTransformResizeFill },
                OperationListItem::Operation { operation: Operation::OpImageTransformFlipHorizontal },
                OperationListItem::Operation { operation: Operation::OpImageTransformFlipVertical },
                OperationListItem::Operation { operation: Operation::OpImageTransformRotate90 },
                OperationListItem::Operation { operation: Operation::OpImageTransformRotate180 },
                OperationListItem::Operation { operation: Operation::OpImageTransformRotate270 },
                OperationListItem::Operation { operation: Operation::OpImageTransformRotateAroundCenter },
                OperationListItem::Operation { operation: Operation::OpImageTransformWarp },
                OperationListItem::Operation { operation: Operation::OpImageTransformDirectionalWarp },
                OperationListItem::Operation { operation: Operation::OpImageTransformSafeTransform },
                OperationListItem::Operation { operation: Operation::OpImageTransformMakeTile },
                OperationListItem::Operation { operation: Operation::OpImageTransformMirror },
                OperationListItem::Operation { operation: Operation::OpImageTransformSeamCarve },
            ]},
            OperationListItem::Category { name: "adjustments".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentContrast },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentGrayscale },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentInvert },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentBrighten },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentHueRotate },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentLevels },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentAutoLevels },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentCurves },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentGradientMap },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentPosterize },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentHistogramScan },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentHistogramRange },
            ]},
            OperationListItem::Category { name: "blur".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentBlur },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentDirectionalBlur },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentRadialBlur },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentSlopeBlur },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentNonUniformBlur },
            ]},
            OperationListItem::Category { name: "filter".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentEdgeDetect },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentEmboss },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentSharpen },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentUnsharpen },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentKuwahara },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentAnisotropicKuwahara },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentBilateral },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentSnn },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentToon },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentMedian },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentGuided },
                OperationListItem::Operation { operation: Operation::OpImageAdjustmentDistance },
            ]},
            OperationListItem::Category { name: "pbr".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImagePbrNormalFromHeight },
                OperationListItem::Operation { operation: Operation::OpImagePbrAoFromHeight },
                OperationListItem::Operation { operation: Operation::OpImagePbrCurvature },
                OperationListItem::Operation { operation: Operation::OpImagePbrHeightBlend },
            ]},
            OperationListItem::Category { name: "channels".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageChannelSplit },
                OperationListItem::Operation { operation: Operation::OpImageChannelMerge },
                OperationListItem::Operation { operation: Operation::OpImageChannelShuffle },
            ]},
            OperationListItem::Category { name: "shapes".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageShapeRectangle },
                OperationListItem::Operation { operation: Operation::OpImageShapeEllipse },
                OperationListItem::Operation { operation: Operation::OpImageShapePolygon },
                OperationListItem::Operation { operation: Operation::OpImageShapeStar },
                OperationListItem::Operation { operation: Operation::OpImageShapeLine },
            ]},
            OperationListItem::Category { name: "patterns".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImagePatternBrick },
                OperationListItem::Operation { operation: Operation::OpImagePatternHexagonal },
                OperationListItem::Operation { operation: Operation::OpImagePatternWeave },
                OperationListItem::Operation { operation: Operation::OpImagePatternTileSampler },
            ]},
            OperationListItem::Category { name: "noise".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageNoiseOpenSimplex },
                OperationListItem::Operation { operation: Operation::OpImageNoiseSuperSimplex },
                OperationListItem::Operation { operation: Operation::OpImageNoisePerlin },
                OperationListItem::Operation { operation: Operation::OpImageNoiseWorleyDistance },
                OperationListItem::Operation { operation: Operation::OpImageNoiseWorleyValue },
                OperationListItem::Operation { operation: Operation::OpImageNoiseBillow },
                OperationListItem::Operation { operation: Operation::OpImageNoiseCylinders },
                OperationListItem::Operation { operation: Operation::OpImageNoiseDomainWarpFbm },
                OperationListItem::Operation { operation: Operation::OpImageNoiseFbm },
                OperationListItem::Operation { operation: Operation::OpImageNoiseHeterogenousMultifractalNoise },
                OperationListItem::Operation { operation: Operation::OpImageNoiseHybridMultifractalNoise },
                OperationListItem::Operation { operation: Operation::OpImageNoiseRidgedMultifractalNoise },
                OperationListItem::Operation { operation: Operation::OpImageNoiseValue },
                OperationListItem::Operation { operation: Operation::OpImageNoiseVoronoiCrack },
                OperationListItem::Operation { operation: Operation::OpImageNoiseVoronoise },
                OperationListItem::Operation { operation: Operation::OpImageNoiseReactionDiffusion },
                OperationListItem::Operation { operation: Operation::OpImageNoiseErosion },
                OperationListItem::Operation { operation: Operation::OpImageNoiseGabor },
                OperationListItem::Operation { operation: Operation::OpImageNoiseGaussian },
                OperationListItem::Operation { operation: Operation::OpImageNoiseCrystal },
                OperationListItem::Operation { operation: Operation::OpImageNoiseClouds },
                OperationListItem::Operation { operation: Operation::OpImageNoisePlasma },
                OperationListItem::Operation { operation: Operation::OpImageNoiseAnisotropic },
                OperationListItem::Operation { operation: Operation::OpImageNoiseDirt },
            ]},
            OperationListItem::Category { name: "cast".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpImageCastToImage },
            ]},
        ]},
        OperationListItem::Category { name: "logic".to_string(), operation_list_items: vec![
            OperationListItem::Category { name: "input".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpLogicInputBool },
            ]},
            OperationListItem::Category { name: "comparison".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpLogicCompareEqual },
                OperationListItem::Operation { operation: Operation::OpLogicCompareNotEqual },
                OperationListItem::Operation { operation: Operation::OpLogicCompareLessThan },
                OperationListItem::Operation { operation: Operation::OpLogicCompareLessEqual },
                OperationListItem::Operation { operation: Operation::OpLogicCompareGreaterThan },
                OperationListItem::Operation { operation: Operation::OpLogicCompareGreaterEqual },
            ]},
            OperationListItem::Category { name: "boolean".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpLogicBoolAnd },
                OperationListItem::Operation { operation: Operation::OpLogicBoolOr },
                OperationListItem::Operation { operation: Operation::OpLogicBoolNot },
                OperationListItem::Operation { operation: Operation::OpLogicBoolXor },
                OperationListItem::Operation { operation: Operation::OpLogicBoolNand },
                OperationListItem::Operation { operation: Operation::OpLogicBoolNor },
            ]},
            OperationListItem::Category { name: "flow".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpLogicFlowSelect },
            ]},
        ]},
        OperationListItem::Category { name: "text".to_string(), operation_list_items: vec![
            OperationListItem::Category { name: "input".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpTextInput },
            ]},
            OperationListItem::Category { name: "manipulation".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpTextAppend },
                OperationListItem::Operation { operation: Operation::OpTextLength },
                OperationListItem::Operation { operation: Operation::OpTextToUppercase },
                OperationListItem::Operation { operation: Operation::OpTextToLowercase },
            ]},
        ]},
        OperationListItem::Category { name: "videos".to_string(), operation_list_items: vec![
            OperationListItem::Category { name: "input".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpVideoInputFile },
            ]},
            OperationListItem::Category { name: "output".to_string(), operation_list_items: vec![
                OperationListItem::Operation { operation: Operation::OpVideoOutputFile },
            ]},
        ]},
        OperationListItem::Subgraph,
    ];
    OperationListItem::sort_alphabetically(&mut list);
    list
}





#[cfg(test)]
#[path = "operations_tests.rs"]
mod tests;
