# Generated by scripts/update_manifests.sh — do not edit by hand.
class Nodemangler < Formula
  desc "Node-based visual programming tool for image and color manipulation"
  homepage "https://nodemangler.com/"
  version "1.0.13"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dan335/nodemangler/releases/download/v1.0.13/nodemangler-v1.0.13-macos-aarch64.tar.gz"
      sha256 "d2dcf6747ee8d53e5af2d4753c77c87feac413405c0b7aff92e30a631c96c627"
    else
      url "https://github.com/dan335/nodemangler/releases/download/v1.0.13/nodemangler-v1.0.13-macos-x86_64.tar.gz"
      sha256 "de22faf5d56b0a2d4659adf27ef8ff0e3c088df6e16e8770c29019e83c080145"
    end
  end

  on_linux do
    url "https://github.com/dan335/nodemangler/releases/download/v1.0.13/nodemangler-v1.0.13-linux-x86_64.tar.gz"
    sha256 "f4c113ce6696956e4a62a45facd80441fe46c85c5b242ceecc05301a81e20b61"
  end

  def install
    bin.install "mangler_gui" => "nodemangler"
    bin.install "mangler_cli" => "mangle"
  end

  def caveats
    <<~TEXT
      The GUI installs as a plain binary, not an .app bundle — launch it with
      `nodemangler` from a terminal. `mangle` is the headless CLI.
    TEXT
  end

  test do
    system bin/"mangle", "--help"
  end
end
