# Generated by scripts/update_manifests.sh — do not edit by hand.
class Nodemangler < Formula
  desc "Node-based visual programming tool for image and color manipulation"
  homepage "https://nodemangler.com/"
  version "1.0.8"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dan335/nodemangler/releases/download/v1.0.8/nodemangler-v1.0.8-macos-aarch64.tar.gz"
      sha256 "9c09e677e84396a078b4627e504373f5f501542c43fc6574d408719599bce2a0"
    else
      url "https://github.com/dan335/nodemangler/releases/download/v1.0.8/nodemangler-v1.0.8-macos-x86_64.tar.gz"
      sha256 "e273db5cef9b5e66c710da19fe34335ec193eb3e9f76f95c822420c9ab36bae6"
    end
  end

  on_linux do
    url "https://github.com/dan335/nodemangler/releases/download/v1.0.8/nodemangler-v1.0.8-linux-x86_64.tar.gz"
    sha256 "b61c75813d8a58609788098d1e27a503b898515b058dc431a2b44344c0a5b81a"
  end

  def install
    bin.install "mangler_gui" => "nodemangler"
    bin.install "mangler_cli" => "mangle"
  end

  def caveats
    <<~TEXT
      The GUI installs as a plain binary, not an .app bundle — launch it with
      `nodemangler` from a terminal. `mangle` is the headless CLI.
    TEXT
  end

  test do
    system bin/"mangle", "--help"
  end
end
