# Generated by scripts/update_manifests.sh — do not edit by hand.
class Nodemangler < Formula
  desc "Node-based visual programming tool for image and color manipulation"
  homepage "https://nodemangler.com/"
  version "1.0.16"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dan335/nodemangler/releases/download/v1.0.16/nodemangler-v1.0.16-macos-aarch64.tar.gz"
      sha256 "15c6267a4b7a09e145189e7bbceec2f41614a10375a9fa8ef3532230a5d86a3d"
    else
      url "https://github.com/dan335/nodemangler/releases/download/v1.0.16/nodemangler-v1.0.16-macos-x86_64.tar.gz"
      sha256 "1e87890b9cbafe466e4e9582fc3b40c39e2b0a9efa88a69a84e2b98d78dce534"
    end
  end

  on_linux do
    url "https://github.com/dan335/nodemangler/releases/download/v1.0.16/nodemangler-v1.0.16-linux-x86_64.tar.gz"
    sha256 "e9317deee198156edf1269219e9dbd7e87acc773049df5f53eab98ef00442f9a"
  end

  def install
    bin.install "mangler_gui" => "nodemangler"
    bin.install "mangler_cli" => "mangle"
  end

  def caveats
    <<~TEXT
      The GUI installs as a plain binary, not an .app bundle — launch it with
      `nodemangler` from a terminal. `mangle` is the headless CLI.
    TEXT
  end

  test do
    system bin/"mangle", "--help"
  end
end
