#!/usr/bin/env bash
# Regenerate the package-manager manifests from a release's archives:
#
#   Formula/nodemangler.rb      Homebrew formula (repo doubles as the tap)
#   bucket/nodemangler.json     Scoop manifest (repo doubles as the bucket)
#   packaging/winget/*.yaml     winget manifest set (submitted to winget-pkgs)
#   packaging/aur/PKGBUILD      AUR package (pushed to the AUR by release.yml)
#   packaging/aur/.SRCINFO      its metadata dump, which the AUR requires
#
# Run automatically by the `manifests` job in .github/workflows/release.yml
# after each release, which commits the result to main. Can also be run by
# hand:
#
#   scripts/update_manifests.sh 1.0.8 /dir/containing/the/release/archives
#
# The archive dir must hold the four `nodemangler-v<version>-*` archives that
# the release workflow published (their SHA-256 hashes go into the manifests).
# CI-only, so there is no .bat twin.
set -euo pipefail

VERSION="${1:?usage: update_manifests.sh <version> <archive-dir>}"
ARCHIVE_DIR="${2:?usage: update_manifests.sh <version> <archive-dir>}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

REPO_URL="https://github.com/dan335/nodemangler"
DOWNLOAD="$REPO_URL/releases/download"
DESC="Node-based visual programming tool for image and color manipulation"

sha() {
    local file="$ARCHIVE_DIR/nodemangler-v$VERSION-$1"
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$file" | cut -d' ' -f1
    else
        shasum -a 256 "$file" | cut -d' ' -f1
    fi
}

MAC_ARM="$(sha macos-aarch64.tar.gz)"
MAC_X64="$(sha macos-x86_64.tar.gz)"
LINUX_X64="$(sha linux-x86_64.tar.gz)"
WIN_X64="$(sha windows-x86_64.zip)"
WIN_X64_UPPER="$(printf '%s' "$WIN_X64" | tr '[:lower:]' '[:upper:]')"

mkdir -p "$REPO_ROOT/Formula" "$REPO_ROOT/bucket" "$REPO_ROOT/packaging/winget" "$REPO_ROOT/packaging/aur"

# A formula rather than a cask: Homebrew quarantines cask downloads, and
# Gatekeeper SIGKILLs quarantined binaries that are only ad-hoc signed (ours
# are, until we notarize). Formula downloads are not quarantined, so the
# binaries run out of the box — and the formula also works with brew on Linux.
cat > "$REPO_ROOT/Formula/nodemangler.rb" <<EOF
# Generated by scripts/update_manifests.sh — do not edit by hand.
class Nodemangler < Formula
  desc "$DESC"
  homepage "https://nodemangler.com/"
  version "$VERSION"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    if Hardware::CPU.arm?
      url "$DOWNLOAD/v$VERSION/nodemangler-v$VERSION-macos-aarch64.tar.gz"
      sha256 "$MAC_ARM"
    else
      url "$DOWNLOAD/v$VERSION/nodemangler-v$VERSION-macos-x86_64.tar.gz"
      sha256 "$MAC_X64"
    end
  end

  on_linux do
    url "$DOWNLOAD/v$VERSION/nodemangler-v$VERSION-linux-x86_64.tar.gz"
    sha256 "$LINUX_X64"
  end

  def install
    bin.install "mangler_gui" => "nodemangler"
    bin.install "mangler_cli" => "mangle"
  end

  def caveats
    <<~TEXT
      The GUI installs as a plain binary, not an .app bundle — launch it with
      \`nodemangler\` from a terminal. \`mangle\` is the headless CLI.
    TEXT
  end

  test do
    system bin/"mangle", "--help"
  end
end
EOF

cat > "$REPO_ROOT/bucket/nodemangler.json" <<EOF
{
    "version": "$VERSION",
    "description": "$DESC",
    "homepage": "https://nodemangler.com/",
    "license": "MIT OR Apache-2.0",
    "url": "$DOWNLOAD/v$VERSION/nodemangler-v$VERSION-windows-x86_64.zip",
    "hash": "$WIN_X64",
    "extract_dir": "nodemangler-v$VERSION-windows-x86_64",
    "bin": [
        ["mangler_gui.exe", "nodemangler"],
        ["mangler_cli.exe", "mangle"]
    ],
    "shortcuts": [
        ["mangler_gui.exe", "NodeMangler"]
    ],
    "checkver": {
        "github": "$REPO_URL"
    },
    "autoupdate": {
        "url": "$DOWNLOAD/v\$version/nodemangler-v\$version-windows-x86_64.zip",
        "extract_dir": "nodemangler-v\$version-windows-x86_64"
    }
}
EOF

cat > "$REPO_ROOT/packaging/winget/DanielPhillips.NodeMangler.yaml" <<EOF
# Generated by scripts/update_manifests.sh — do not edit by hand.
PackageIdentifier: DanielPhillips.NodeMangler
PackageVersion: $VERSION
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
EOF

cat > "$REPO_ROOT/packaging/winget/DanielPhillips.NodeMangler.installer.yaml" <<EOF
# Generated by scripts/update_manifests.sh — do not edit by hand.
PackageIdentifier: DanielPhillips.NodeMangler
PackageVersion: $VERSION
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: nodemangler-v$VERSION-windows-x86_64\mangler_gui.exe
  PortableCommandAlias: nodemangler
- RelativeFilePath: nodemangler-v$VERSION-windows-x86_64\mangler_cli.exe
  PortableCommandAlias: mangle
Installers:
- Architecture: x64
  InstallerUrl: $DOWNLOAD/v$VERSION/nodemangler-v$VERSION-windows-x86_64.zip
  InstallerSha256: $WIN_X64_UPPER
ManifestType: installer
ManifestVersion: 1.6.0
EOF

cat > "$REPO_ROOT/packaging/winget/DanielPhillips.NodeMangler.locale.en-US.yaml" <<EOF
# Generated by scripts/update_manifests.sh — do not edit by hand.
PackageIdentifier: DanielPhillips.NodeMangler
PackageVersion: $VERSION
PackageLocale: en-US
Publisher: Daniel Phillips
PublisherUrl: https://github.com/dan335
PublisherSupportUrl: $REPO_URL/issues
PackageName: NodeMangler
PackageUrl: https://nodemangler.com/
License: MIT OR Apache-2.0
LicenseUrl: $REPO_URL/blob/main/LICENSE.md
ShortDescription: $DESC
Moniker: nodemangler
Tags:
- image-editor
- node-editor
- procedural
- texture
ManifestType: defaultLocale
ManifestVersion: 1.6.0
EOF

# AUR package `nodemangler-bin`: repackages the same linux-x86_64 archive the
# releases page serves, so installing is a download instead of a full Rust
# build. The archive carries the .desktop file and the icon (put there by the
# release workflow's Linux packaging step) so the package registers a proper
# menu entry.
#
# The binaries install under the Homebrew/Scoop names — `nodemangler` for the
# GUI, `mangle` for the CLI — so the commands match on every platform.
#
# If this PKGBUILD gains fields, add them to the .SRCINFO block below too: the
# AUR reads that file, not the PKGBUILD, and nothing here runs makepkg to keep
# them in sync. Verify a change on an Arch box with
# `cd packaging/aur && makepkg --printsrcinfo | diff - .SRCINFO`.
ARCHIVE_STEM="nodemangler-v$VERSION-linux-x86_64"
AUR_URL="$DOWNLOAD/v$VERSION/$ARCHIVE_STEM.tar.gz"

cat > "$REPO_ROOT/packaging/aur/PKGBUILD" <<EOF
# Maintainer: Daniel Phillips <danphi@gmail.com>
# Generated by scripts/update_manifests.sh — do not edit by hand.
pkgname=nodemangler-bin
pkgver=$VERSION
pkgrel=1
pkgdesc="$DESC"
arch=('x86_64')
url="https://nodemangler.com/"
license=('MIT' 'Apache-2.0')
# Read off the dependency tree rather than off ldd: winit's X11/Wayland
# backends and glutin's GL loader dlopen almost all of this, so it never shows
# up as an ELF NEEDED entry. Note there is no GTK and no OpenSSL in the tree --
# rfd 0.17 drives the XDG portal over zbus and reqwest 0.13 uses rustls -- even
# though release.yml still apt-installs libgtk-3-dev/libssl-dev to build.
depends=('glibc' 'gcc-libs' 'libglvnd' 'libxkbcommon' 'wayland' 'libx11'
         'libxcursor' 'libxrandr' 'libxi' 'hicolor-icon-theme'
         'xdg-desktop-portal')
optdepends=('xdg-desktop-portal-gtk: file dialogs on desktops with no portal backend of their own')
provides=('nodemangler' 'mangle')
conflicts=('nodemangler')
# Prebuilt upstream binaries: nothing here for makepkg to strip or to split
# debug symbols out of.
options=('!strip' '!debug')
_archive="$ARCHIVE_STEM"
source=("\$_archive.tar.gz::$AUR_URL")
sha256sums=('$LINUX_X64')

package() {
    cd "\$_archive"

    install -Dm755 mangler_gui "\$pkgdir/usr/bin/nodemangler"
    install -Dm755 mangler_cli "\$pkgdir/usr/bin/mangle"

    install -Dm644 README.md "\$pkgdir/usr/share/doc/\$pkgname/README.md"
    install -Dm644 LICENSE.md "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE.md"
    install -Dm644 nodemangler.png "\$pkgdir/usr/share/icons/hicolor/256x256/apps/nodemangler.png"

    # The archived .desktop is the AppImage's, which launches \`mangler_gui\`;
    # this package installs the GUI as \`nodemangler\` instead.
    install -Dm644 nodemangler.desktop "\$pkgdir/usr/share/applications/nodemangler.desktop"
    sed -i 's/^Exec=.*/Exec=nodemangler/' "\$pkgdir/usr/share/applications/nodemangler.desktop"
}
EOF

# Field order mirrors `makepkg --printsrcinfo`; the indent is a literal tab.
cat > "$REPO_ROOT/packaging/aur/.SRCINFO" <<EOF
pkgbase = nodemangler-bin
	pkgdesc = $DESC
	pkgver = $VERSION
	pkgrel = 1
	url = https://nodemangler.com/
	arch = x86_64
	license = MIT
	license = Apache-2.0
	depends = glibc
	depends = gcc-libs
	depends = libglvnd
	depends = libxkbcommon
	depends = wayland
	depends = libx11
	depends = libxcursor
	depends = libxrandr
	depends = libxi
	depends = hicolor-icon-theme
	depends = xdg-desktop-portal
	optdepends = xdg-desktop-portal-gtk: file dialogs on desktops with no portal backend of their own
	provides = nodemangler
	provides = mangle
	conflicts = nodemangler
	options = !strip
	options = !debug
	source = $ARCHIVE_STEM.tar.gz::$AUR_URL
	sha256sums = $LINUX_X64

pkgname = nodemangler-bin
EOF

echo "Manifests updated for v$VERSION:"
echo "  macos-aarch64  $MAC_ARM"
echo "  macos-x86_64   $MAC_X64"
echo "  linux-x86_64   $LINUX_X64"
echo "  windows-x86_64 $WIN_X64"
