#!/usr/bin/env bash
# Regenerate the package-manager manifests from a release's archives:
#
#   Formula/nodemangler.rb      Homebrew formula (repo doubles as the tap)
#   bucket/nodemangler.json     Scoop manifest (repo doubles as the bucket)
#   packaging/winget/*.yaml     winget manifest set (submitted to winget-pkgs)
#
# Run automatically by the `manifests` job in .github/workflows/release.yml
# after each release, which commits the result to main. Can also be run by
# hand:
#
#   scripts/update_manifests.sh 1.0.8 /dir/containing/the/release/archives
#
# The archive dir must hold the four `nodemangler-v<version>-*` archives that
# the release workflow published (their SHA-256 hashes go into the manifests).
# CI-only, so there is no .bat twin.
set -euo pipefail

VERSION="${1:?usage: update_manifests.sh <version> <archive-dir>}"
ARCHIVE_DIR="${2:?usage: update_manifests.sh <version> <archive-dir>}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

REPO_URL="https://github.com/dan335/nodemangler"
DOWNLOAD="$REPO_URL/releases/download"
DESC="Node-based visual programming tool for image and color manipulation"

sha() {
    local file="$ARCHIVE_DIR/nodemangler-v$VERSION-$1"
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$file" | cut -d' ' -f1
    else
        shasum -a 256 "$file" | cut -d' ' -f1
    fi
}

MAC_ARM="$(sha macos-aarch64.tar.gz)"
MAC_X64="$(sha macos-x86_64.tar.gz)"
LINUX_X64="$(sha linux-x86_64.tar.gz)"
WIN_X64="$(sha windows-x86_64.zip)"
WIN_X64_UPPER="$(printf '%s' "$WIN_X64" | tr '[:lower:]' '[:upper:]')"

mkdir -p "$REPO_ROOT/Formula" "$REPO_ROOT/bucket" "$REPO_ROOT/packaging/winget"

# A formula rather than a cask: Homebrew quarantines cask downloads, and
# Gatekeeper SIGKILLs quarantined binaries that are only ad-hoc signed (ours
# are, until we notarize). Formula downloads are not quarantined, so the
# binaries run out of the box — and the formula also works with brew on Linux.
cat > "$REPO_ROOT/Formula/nodemangler.rb" <<EOF
# Generated by scripts/update_manifests.sh — do not edit by hand.
class Nodemangler < Formula
  desc "$DESC"
  homepage "https://nodemangler.com/"
  version "$VERSION"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    if Hardware::CPU.arm?
      url "$DOWNLOAD/v$VERSION/nodemangler-v$VERSION-macos-aarch64.tar.gz"
      sha256 "$MAC_ARM"
    else
      url "$DOWNLOAD/v$VERSION/nodemangler-v$VERSION-macos-x86_64.tar.gz"
      sha256 "$MAC_X64"
    end
  end

  on_linux do
    url "$DOWNLOAD/v$VERSION/nodemangler-v$VERSION-linux-x86_64.tar.gz"
    sha256 "$LINUX_X64"
  end

  def install
    bin.install "mangler_gui" => "nodemangler"
    bin.install "mangler_cli" => "mangle"
  end

  def caveats
    <<~TEXT
      The GUI installs as a plain binary, not an .app bundle — launch it with
      \`nodemangler\` from a terminal. \`mangle\` is the headless CLI.
    TEXT
  end

  test do
    system bin/"mangle", "--help"
  end
end
EOF

cat > "$REPO_ROOT/bucket/nodemangler.json" <<EOF
{
    "version": "$VERSION",
    "description": "$DESC",
    "homepage": "https://nodemangler.com/",
    "license": "MIT OR Apache-2.0",
    "url": "$DOWNLOAD/v$VERSION/nodemangler-v$VERSION-windows-x86_64.zip",
    "hash": "$WIN_X64",
    "extract_dir": "nodemangler-v$VERSION-windows-x86_64",
    "bin": [
        ["mangler_gui.exe", "nodemangler"],
        ["mangler_cli.exe", "mangle"]
    ],
    "shortcuts": [
        ["mangler_gui.exe", "NodeMangler"]
    ],
    "checkver": {
        "github": "$REPO_URL"
    },
    "autoupdate": {
        "url": "$DOWNLOAD/v\$version/nodemangler-v\$version-windows-x86_64.zip",
        "extract_dir": "nodemangler-v\$version-windows-x86_64"
    }
}
EOF

cat > "$REPO_ROOT/packaging/winget/DanielPhillips.NodeMangler.yaml" <<EOF
# Generated by scripts/update_manifests.sh — do not edit by hand.
PackageIdentifier: DanielPhillips.NodeMangler
PackageVersion: $VERSION
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
EOF

cat > "$REPO_ROOT/packaging/winget/DanielPhillips.NodeMangler.installer.yaml" <<EOF
# Generated by scripts/update_manifests.sh — do not edit by hand.
PackageIdentifier: DanielPhillips.NodeMangler
PackageVersion: $VERSION
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: nodemangler-v$VERSION-windows-x86_64\mangler_gui.exe
  PortableCommandAlias: nodemangler
- RelativeFilePath: nodemangler-v$VERSION-windows-x86_64\mangler_cli.exe
  PortableCommandAlias: mangle
Installers:
- Architecture: x64
  InstallerUrl: $DOWNLOAD/v$VERSION/nodemangler-v$VERSION-windows-x86_64.zip
  InstallerSha256: $WIN_X64_UPPER
ManifestType: installer
ManifestVersion: 1.6.0
EOF

cat > "$REPO_ROOT/packaging/winget/DanielPhillips.NodeMangler.locale.en-US.yaml" <<EOF
# Generated by scripts/update_manifests.sh — do not edit by hand.
PackageIdentifier: DanielPhillips.NodeMangler
PackageVersion: $VERSION
PackageLocale: en-US
Publisher: Daniel Phillips
PublisherUrl: https://github.com/dan335
PublisherSupportUrl: $REPO_URL/issues
PackageName: NodeMangler
PackageUrl: https://nodemangler.com/
License: MIT OR Apache-2.0
LicenseUrl: $REPO_URL/blob/main/LICENSE.md
ShortDescription: $DESC
Moniker: nodemangler
Tags:
- image-editor
- node-editor
- procedural
- texture
ManifestType: defaultLocale
ManifestVersion: 1.6.0
EOF

echo "Manifests updated for v$VERSION:"
echo "  macos-aarch64  $MAC_ARM"
echo "  macos-x86_64   $MAC_X64"
echo "  windows-x86_64 $WIN_X64"
